package ar.com.santander.rio.mbanking.app.ui.activities;

import android.widget.Button;
import android.widget.RelativeLayout;
import android.widget.TextView;
import ar.com.santander.rio.mbanking.R;
import ar.com.santander.rio.mbanking.view.AmountView;
import butterknife.ButterKnife.Finder;

public class DetalleCuotaActivity$$ViewInjector {
    public static void inject(Finder finder, DetalleCuotaActivity detalleCuotaActivity, Object obj) {
        detalleCuotaActivity.creditTitle = (TextView) finder.findRequiredView(obj, R.id.ID_4688_SEGUROS_CONTRATAR_SEGURO, "field 'creditTitle'");
        detalleCuotaActivity.creditHeaderTitle = (TextView) finder.findRequiredView(obj, R.id.credit_header_title, "field 'creditHeaderTitle'");
        detalleCuotaActivity.creditHeaderData = (AmountView) finder.findRequiredView(obj, R.id.credit_header_data, "field 'creditHeaderData'");
        detalleCuotaActivity.creditHeaderDesc = (TextView) finder.findRequiredView(obj, R.id.credit_header_desc, "field 'creditHeaderDesc'");
        detalleCuotaActivity.saldoAnteriorDeCapital = (TextView) finder.findRequiredView(obj, R.id.F10_01_lbl_intereses12, "field 'saldoAnteriorDeCapital'");
        detalleCuotaActivity.loanNumberRl = (RelativeLayout) finder.findRequiredView(obj, R.id.loan_number_rl, "field 'loanNumberRl'");
        detalleCuotaActivity.loanNumberData = (TextView) finder.findRequiredView(obj, R.id.loan_number_data, "field 'loanNumberData'");
        detalleCuotaActivity.accountRl = (RelativeLayout) finder.findRequiredView(obj, R.id.account_rl, "field 'accountRl'");
        detalleCuotaActivity.accountData = (TextView) finder.findRequiredView(obj, R.id.account_data, "field 'accountData'");
        detalleCuotaActivity.cuotaNumberRl = (RelativeLayout) finder.findRequiredView(obj, R.id.cuota_number_rl, "field 'cuotaNumberRl'");
        detalleCuotaActivity.cuotaNumberData = (TextView) finder.findRequiredView(obj, R.id.cuota_number_data, "field 'cuotaNumberData'");
        detalleCuotaActivity.dateRl = (RelativeLayout) finder.findRequiredView(obj, R.id.date_rl, "field 'dateRl'");
        detalleCuotaActivity.dateData = (TextView) finder.findRequiredView(obj, R.id.date_data, "field 'dateData'");
        detalleCuotaActivity.saldoAnteriorSinAjustarRl = (RelativeLayout) finder.findRequiredView(obj, R.id.saldo_anterior_s_ajustar_rl, "field 'saldoAnteriorSinAjustarRl'");
        detalleCuotaActivity.saldoAnteriorSinAjustarData = (TextView) finder.findRequiredView(obj, R.id.saldo_anterior_s_ajustar_data, "field 'saldoAnteriorSinAjustarData'");
        detalleCuotaActivity.fechaVtoRl = (RelativeLayout) finder.findRequiredView(obj, R.id.fecha_vto_rl, "field 'fechaVtoRl'");
        detalleCuotaActivity.fechaVtoData = (TextView) finder.findRequiredView(obj, R.id.fecha_vto_data, "field 'fechaVtoData'");
        detalleCuotaActivity.coeficienteRl = (RelativeLayout) finder.findRequiredView(obj, R.id.coeficiente_rl, "field 'coeficienteRl'");
        detalleCuotaActivity.coeficienteData = (TextView) finder.findRequiredView(obj, R.id.coeficiente_data, "field 'coeficienteData'");
        detalleCuotaActivity.interesPesosUvaRl = (RelativeLayout) finder.findRequiredView(obj, R.id.interes_pesos_uva_rl, "field 'interesPesosUvaRl'");
        detalleCuotaActivity.interesPesosUvaData = (TextView) finder.findRequiredView(obj, R.id.interes_pesos_uva_data, "field 'interesPesosUvaData'");
        detalleCuotaActivity.valorUvaRl = (RelativeLayout) finder.findRequiredView(obj, R.id.valor_uva_rl, "field 'valorUvaRl'");
        detalleCuotaActivity.valorUvaData = (TextView) finder.findRequiredView(obj, R.id.valor_uva_data, "field 'valorUvaData'");
        detalleCuotaActivity.capitalUvaRl = (RelativeLayout) finder.findRequiredView(obj, R.id.capital_uva_rl, "field 'capitalUvaRl'");
        detalleCuotaActivity.capitalUvaData = (TextView) finder.findRequiredView(obj, R.id.capital_uva_data, "field 'capitalUvaData'");
        detalleCuotaActivity.interesesUvaRl = (RelativeLayout) finder.findRequiredView(obj, R.id.intereses_uva_rl, "field 'interesesUvaRl'");
        detalleCuotaActivity.interesesUvaData = (TextView) finder.findRequiredView(obj, R.id.intereses_uva_data, "field 'interesesUvaData'");
        detalleCuotaActivity.relativeImporteDeCuotaPuraUVAS = (RelativeLayout) finder.findRequiredView(obj, R.id.relativeImporteDeCuotaPuraUVAS, "field 'relativeImporteDeCuotaPuraUVAS'");
        detalleCuotaActivity.textViewImporteDeCuotaPuraUVAS_data = (TextView) finder.findRequiredView(obj, R.id.textViewImporteDeCuotaPuraUVAS_data, "field 'textViewImporteDeCuotaPuraUVAS_data'");
        detalleCuotaActivity.fechaCotizacionDeUVAs_rl = (RelativeLayout) finder.findRequiredView(obj, R.id.fechaCotizacionDeUVAs_rl, "field 'fechaCotizacionDeUVAs_rl'");
        detalleCuotaActivity.fechaDeCotizacionDeUVAs_data = (TextView) finder.findRequiredView(obj, R.id.fechaDeCotizacionDeUVAs_data, "field 'fechaDeCotizacionDeUVAs_data'");
        detalleCuotaActivity.cuotaValueRl = (RelativeLayout) finder.findRequiredView(obj, R.id.cuota_value_rl, "field 'cuotaValueRl'");
        detalleCuotaActivity.cuotaValueData = (TextView) finder.findRequiredView(obj, R.id.cuota_value_data, "field 'cuotaValueData'");
        detalleCuotaActivity.capitalRl = (RelativeLayout) finder.findRequiredView(obj, R.id.capital_rl, "field 'capitalRl'");
        detalleCuotaActivity.capitalData = (TextView) finder.findRequiredView(obj, R.id.capital_data, "field 'capitalData'");
        detalleCuotaActivity.ajusteCapitalMoraRl = (RelativeLayout) finder.findRequiredView(obj, R.id.ajuste_capital_mora_rl, "field 'ajusteCapitalMoraRl'");
        detalleCuotaActivity.ajusteCapitalMoraData = (TextView) finder.findRequiredView(obj, R.id.ajuste_capital_mora_data, "field 'ajusteCapitalMoraData'");
        detalleCuotaActivity.interesesCompRl = (RelativeLayout) finder.findRequiredView(obj, R.id.intereses_comp_rl, "field 'interesesCompRl'");
        detalleCuotaActivity.interesesCompData = (TextView) finder.findRequiredView(obj, R.id.intereses_comp_data, "field 'interesesCompData'");
        detalleCuotaActivity.interesesPunitoriosRl = (RelativeLayout) finder.findRequiredView(obj, R.id.intereses_punitorios_rl, "field 'interesesPunitoriosRl'");
        detalleCuotaActivity.interesesPunitoriosData = (TextView) finder.findRequiredView(obj, R.id.intereses_punitorios_data, "field 'interesesPunitoriosData'");
        detalleCuotaActivity.cargoSeguroVidaRl = (RelativeLayout) finder.findRequiredView(obj, R.id.cargo_seguro_vida_rl, "field 'cargoSeguroVidaRl'");
        detalleCuotaActivity.cargoSeguroVidaData = (TextView) finder.findRequiredView(obj, R.id.cargo_seguro_vida_data, "field 'cargoSeguroVidaData'");
        detalleCuotaActivity.taxesRl = (RelativeLayout) finder.findRequiredView(obj, R.id.taxes_rl, "field 'taxesRl'");
        detalleCuotaActivity.taxesData = (TextView) finder.findRequiredView(obj, R.id.taxes_data, "field 'taxesData'");
        detalleCuotaActivity.goodAssuranceRl = (RelativeLayout) finder.findRequiredView(obj, R.id.good_assurance_rl, "field 'goodAssuranceRl'");
        detalleCuotaActivity.goodAssuranceData = (TextView) finder.findRequiredView(obj, R.id.good_assurance_data, "field 'goodAssuranceData'");
        detalleCuotaActivity.seguroIncendioRl = (RelativeLayout) finder.findRequiredView(obj, R.id.seguro_incendio_rl, "field 'seguroIncendioRl'");
        detalleCuotaActivity.seguroIncendioData = (TextView) finder.findRequiredView(obj, R.id.seguro_incendio_data, "field 'seguroIncendioData'");
        detalleCuotaActivity.iva_rl = (RelativeLayout) finder.findRequiredView(obj, R.id.iva_rl, "field 'iva_rl'");
        detalleCuotaActivity.textViewIVAData = (TextView) finder.findRequiredView(obj, R.id.textViewIVAData, "field 'textViewIVAData'");
        detalleCuotaActivity.disponible_uso_rl = (RelativeLayout) finder.findRequiredView(obj, R.id.disponible_uso_rl, "field 'disponible_uso_rl'");
        detalleCuotaActivity.disponible_uso_data = (TextView) finder.findRequiredView(obj, R.id.disponible_uso_data, "field 'disponible_uso_data'");
        detalleCuotaActivity.linea_credito_rl = (RelativeLayout) finder.findRequiredView(obj, R.id.linea_credito_rl, "field 'linea_credito_rl'");
        detalleCuotaActivity.linea_credito_data = (TextView) finder.findRequiredView(obj, R.id.linea_credito_data, "field 'linea_credito_data'");
        detalleCuotaActivity.teaRl = (RelativeLayout) finder.findRequiredView(obj, R.id.tea_rl, "field 'teaRl'");
        detalleCuotaActivity.teaData = (TextView) finder.findRequiredView(obj, R.id.tea_data, "field 'teaData'");
        detalleCuotaActivity.tnaRl = (RelativeLayout) finder.findRequiredView(obj, R.id.tna_rl, "field 'tnaRl'");
        detalleCuotaActivity.tnaData = (TextView) finder.findRequiredView(obj, R.id.tna_data, "field 'tnaData'");
        detalleCuotaActivity.CFTNARl = (RelativeLayout) finder.findRequiredView(obj, R.id.CFTNA_rl, "field 'CFTNARl'");
        detalleCuotaActivity.CFTNAData = (TextView) finder.findRequiredView(obj, R.id.CFTNA_data, "field 'CFTNAData'");
        detalleCuotaActivity.CFTNAsIvaRl = (RelativeLayout) finder.findRequiredView(obj, R.id.CFTNA_sIva_rl, "field 'CFTNAsIvaRl'");
        detalleCuotaActivity.CFTNAsIvaData = (TextView) finder.findRequiredView(obj, R.id.CFTNA_sIva_data, "field 'CFTNAsIvaData'");
        detalleCuotaActivity.leyendaRl = (RelativeLayout) finder.findRequiredView(obj, R.id.leyenda_rl, "field 'leyendaRl'");
        detalleCuotaActivity.leyenda_int_punitorios = (TextView) finder.findRequiredView(obj, R.id.leyenda_int_punitorios, "field 'leyenda_int_punitorios'");
        detalleCuotaActivity.leyendaData = (TextView) finder.findRequiredView(obj, R.id.leyenda_data, "field 'leyendaData'");
        detalleCuotaActivity.leyenda_tasa_detalle = (TextView) finder.findRequiredView(obj, R.id.leyenda_tasa_detalle, "field 'leyenda_tasa_detalle'");
        detalleCuotaActivity.detailNextButton = (Button) finder.findRequiredView(obj, R.id.tenencia_de_prestamos_detail_button, "field 'detailNextButton'");
    }

    public static void reset(DetalleCuotaActivity detalleCuotaActivity) {
        detalleCuotaActivity.creditTitle = null;
        detalleCuotaActivity.creditHeaderTitle = null;
        detalleCuotaActivity.creditHeaderData = null;
        detalleCuotaActivity.creditHeaderDesc = null;
        detalleCuotaActivity.saldoAnteriorDeCapital = null;
        detalleCuotaActivity.loanNumberRl = null;
        detalleCuotaActivity.loanNumberData = null;
        detalleCuotaActivity.accountRl = null;
        detalleCuotaActivity.accountData = null;
        detalleCuotaActivity.cuotaNumberRl = null;
        detalleCuotaActivity.cuotaNumberData = null;
        detalleCuotaActivity.dateRl = null;
        detalleCuotaActivity.dateData = null;
        detalleCuotaActivity.saldoAnteriorSinAjustarRl = null;
        detalleCuotaActivity.saldoAnteriorSinAjustarData = null;
        detalleCuotaActivity.fechaVtoRl = null;
        detalleCuotaActivity.fechaVtoData = null;
        detalleCuotaActivity.coeficienteRl = null;
        detalleCuotaActivity.coeficienteData = null;
        detalleCuotaActivity.interesPesosUvaRl = null;
        detalleCuotaActivity.interesPesosUvaData = null;
        detalleCuotaActivity.valorUvaRl = null;
        detalleCuotaActivity.valorUvaData = null;
        detalleCuotaActivity.capitalUvaRl = null;
        detalleCuotaActivity.capitalUvaData = null;
        detalleCuotaActivity.interesesUvaRl = null;
        detalleCuotaActivity.interesesUvaData = null;
        detalleCuotaActivity.relativeImporteDeCuotaPuraUVAS = null;
        detalleCuotaActivity.textViewImporteDeCuotaPuraUVAS_data = null;
        detalleCuotaActivity.fechaCotizacionDeUVAs_rl = null;
        detalleCuotaActivity.fechaDeCotizacionDeUVAs_data = null;
        detalleCuotaActivity.cuotaValueRl = null;
        detalleCuotaActivity.cuotaValueData = null;
        detalleCuotaActivity.capitalRl = null;
        detalleCuotaActivity.capitalData = null;
        detalleCuotaActivity.ajusteCapitalMoraRl = null;
        detalleCuotaActivity.ajusteCapitalMoraData = null;
        detalleCuotaActivity.interesesCompRl = null;
        detalleCuotaActivity.interesesCompData = null;
        detalleCuotaActivity.interesesPunitoriosRl = null;
        detalleCuotaActivity.interesesPunitoriosData = null;
        detalleCuotaActivity.cargoSeguroVidaRl = null;
        detalleCuotaActivity.cargoSeguroVidaData = null;
        detalleCuotaActivity.taxesRl = null;
        detalleCuotaActivity.taxesData = null;
        detalleCuotaActivity.goodAssuranceRl = null;
        detalleCuotaActivity.goodAssuranceData = null;
        detalleCuotaActivity.seguroIncendioRl = null;
        detalleCuotaActivity.seguroIncendioData = null;
        detalleCuotaActivity.iva_rl = null;
        detalleCuotaActivity.textViewIVAData = null;
        detalleCuotaActivity.disponible_uso_rl = null;
        detalleCuotaActivity.disponible_uso_data = null;
        detalleCuotaActivity.linea_credito_rl = null;
        detalleCuotaActivity.linea_credito_data = null;
        detalleCuotaActivity.teaRl = null;
        detalleCuotaActivity.teaData = null;
        detalleCuotaActivity.tnaRl = null;
        detalleCuotaActivity.tnaData = null;
        detalleCuotaActivity.CFTNARl = null;
        detalleCuotaActivity.CFTNAData = null;
        detalleCuotaActivity.CFTNAsIvaRl = null;
        detalleCuotaActivity.CFTNAsIvaData = null;
        detalleCuotaActivity.leyendaRl = null;
        detalleCuotaActivity.leyenda_int_punitorios = null;
        detalleCuotaActivity.leyendaData = null;
        detalleCuotaActivity.leyenda_tasa_detalle = null;
        detalleCuotaActivity.detailNextButton = null;
    }
}
