package ar.com.santander.rio.mbanking.app.ui.activities;

import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.ViewFlipper;
import ar.com.santander.rio.mbanking.R;
import ar.com.santander.rio.mbanking.view.NumericEditTextWithPrefixAccesibility;
import butterknife.ButterKnife.Finder;

public class NuevoDebinActivity$$ViewInjector {
    public static void inject(Finder finder, NuevoDebinActivity nuevoDebinActivity, Object obj) {
        nuevoDebinActivity.mControlPager = (ViewFlipper) finder.findRequiredView(obj, R.id.nuevo_debin_view_flipper, "field 'mControlPager'");
        nuevoDebinActivity.layout_sinCuentas = (RelativeLayout) finder.findRequiredView(obj, R.id.F32_16_relative_sinCuentas, "field 'layout_sinCuentas'");
        nuevoDebinActivity.txtSeleccionCBU = (TextView) finder.findRequiredView(obj, R.id.seleccionCBU, "field 'txtSeleccionCBU'");
        nuevoDebinActivity.imgDestinoSeleccionado = (ImageView) finder.findRequiredView(obj, R.id.imgDestinoSeleccionado, "field 'imgDestinoSeleccionado'");
        nuevoDebinActivity.txtAyuda = (TextView) finder.findRequiredView(obj, R.id.txtAyuda, "field 'txtAyuda'");
        nuevoDebinActivity.btnVerificar = (Button) finder.findRequiredView(obj, R.id.F32_10_btn_verificar, "field 'btnVerificar'");
        nuevoDebinActivity.selectorCBU = (RelativeLayout) finder.findRequiredView(obj, R.id.selectorCBU, "field 'selectorCBU'");
        nuevoDebinActivity.etCBU = (EditText) finder.findRequiredView(obj, R.id.editTextCBU, "field 'etCBU'");
        nuevoDebinActivity.lblTitle = (TextView) finder.findRequiredView(obj, R.id.F32_10_txt_title, "field 'lblTitle'");
        nuevoDebinActivity.lblGenerarDebinTitle = (TextView) finder.findRequiredView(obj, R.id.F32_13_txt_title, "field 'lblGenerarDebinTitle'");
        nuevoDebinActivity.lblComprador = (TextView) finder.findRequiredView(obj, R.id.F32_13_comprador, "field 'lblComprador'");
        nuevoDebinActivity.lblCuit = (TextView) finder.findRequiredView(obj, R.id.F32_13_LBL_CUIT, "field 'lblCuit'");
        nuevoDebinActivity.lblAlias = (TextView) finder.findRequiredView(obj, R.id.F32_13_LBL_DATA_ALIAS, "field 'lblAlias'");
        nuevoDebinActivity.lblBanco = (TextView) finder.findRequiredView(obj, R.id.F32_13_LBL_DATA_BANCO, "field 'lblBanco'");
        nuevoDebinActivity.lblCBU = (TextView) finder.findRequiredView(obj, R.id.F32_13_LBL_DATA_CBU, "field 'lblCBU'");
        nuevoDebinActivity.lblConcepto = (TextView) finder.findRequiredView(obj, R.id.F32_13_LBL_DATA_CONCEPTO, "field 'lblConcepto'");
        nuevoDebinActivity.lblDescripcion = (EditText) finder.findRequiredView(obj, R.id.F32_13_LBL_DATA_DESCRIPCION, "field 'lblDescripcion'");
        nuevoDebinActivity.lblCtaAcreditacion = (TextView) finder.findRequiredView(obj, R.id.F32_13_LBL_DATA_CTA_ACREDITACION, "field 'lblCtaAcreditacion'");
        nuevoDebinActivity.lblFechaVto = (TextView) finder.findRequiredView(obj, R.id.F32_13_LBL_DATA_FECHA_VENCIMIENTO, "field 'lblFechaVto'");
        nuevoDebinActivity.etImporte = (NumericEditTextWithPrefixAccesibility) finder.findRequiredView(obj, R.id.F32_13_importe, "field 'etImporte'");
        nuevoDebinActivity.rowAlias = (LinearLayout) finder.findRequiredView(obj, R.id.F32_13_row_alias, "field 'rowAlias'");
        nuevoDebinActivity.btnContinuar = (Button) finder.findRequiredView(obj, R.id.F32_13_btn_continuar, "field 'btnContinuar'");
        nuevoDebinActivity.rowCBU = (LinearLayout) finder.findRequiredView(obj, R.id.F32_13_row_cbu, "field 'rowCBU'");
        nuevoDebinActivity.rowBanco = (LinearLayout) finder.findRequiredView(obj, R.id.F32_13_row_banco, "field 'rowBanco'");
        nuevoDebinActivity.leyendaGenerarDebin = (TextView) finder.findRequiredView(obj, R.id.F32_13_LBL_DATA_Leyenda, "field 'leyendaGenerarDebin'");
        nuevoDebinActivity.lblConfirmarTitle = (TextView) finder.findRequiredView(obj, R.id.F32_14_txt_title, "field 'lblConfirmarTitle'");
        nuevoDebinActivity.lblCompradorC = (TextView) finder.findRequiredView(obj, R.id.F32_14_comprador, "field 'lblCompradorC'");
        nuevoDebinActivity.lblCuitC = (TextView) finder.findRequiredView(obj, R.id.F32_14_LBL_CUIT, "field 'lblCuitC'");
        nuevoDebinActivity.lblAliasC = (TextView) finder.findRequiredView(obj, R.id.F32_14_LBL_DATA_ALIAS, "field 'lblAliasC'");
        nuevoDebinActivity.lblBancoC = (TextView) finder.findRequiredView(obj, R.id.F32_14_LBL_DATA_BANCO, "field 'lblBancoC'");
        nuevoDebinActivity.lblCBUC = (TextView) finder.findRequiredView(obj, R.id.F32_14_LBL_DATA_CBU, "field 'lblCBUC'");
        nuevoDebinActivity.lblConceptoC = (TextView) finder.findRequiredView(obj, R.id.F32_14_LBL_DATA_CONCEPTO, "field 'lblConceptoC'");
        nuevoDebinActivity.lblDescripcionC = (TextView) finder.findRequiredView(obj, R.id.F32_14_LBL_DATA_DESCRIPCION, "field 'lblDescripcionC'");
        nuevoDebinActivity.lblCtaAcreditacionC = (TextView) finder.findRequiredView(obj, R.id.F32_14_LBL_DATA_CTA_ACREDITACION, "field 'lblCtaAcreditacionC'");
        nuevoDebinActivity.lblFechaVtoC = (TextView) finder.findRequiredView(obj, R.id.F32_14_LBL_DATA_FECHA_VENCIMIENTO, "field 'lblFechaVtoC'");
        nuevoDebinActivity.etImporteC = (TextView) finder.findRequiredView(obj, R.id.F32_14_importe, "field 'etImporteC'");
        nuevoDebinActivity.rowAliasC = (LinearLayout) finder.findRequiredView(obj, R.id.F32_14_row_alias, "field 'rowAliasC'");
        nuevoDebinActivity.btnConfirmar = (Button) finder.findRequiredView(obj, R.id.F32_14_btn_confirmar, "field 'btnConfirmar'");
        nuevoDebinActivity.rowDescripcion = (LinearLayout) finder.findRequiredView(obj, R.id.F32_14_row_descripcion, "field 'rowDescripcion'");
        nuevoDebinActivity.rowCBUC = (LinearLayout) finder.findRequiredView(obj, R.id.F32_14_row_cbu, "field 'rowCBUC'");
        nuevoDebinActivity.rowBancoC = (LinearLayout) finder.findRequiredView(obj, R.id.F32_14_row_banco, "field 'rowBancoC'");
        nuevoDebinActivity.leyendaConfirmarDebin = (TextView) finder.findRequiredView(obj, R.id.F32_14_LBL_DATA_Leyenda, "field 'leyendaConfirmarDebin'");
        nuevoDebinActivity.row_fechaOperacion = (LinearLayout) finder.findRequiredView(obj, R.id.F32_15_row_fechaOperacion, "field 'row_fechaOperacion'");
        nuevoDebinActivity.row_nroComprobante = (LinearLayout) finder.findRequiredView(obj, R.id.F32_15_row_nroComprobante, "field 'row_nroComprobante'");
        nuevoDebinActivity.lblFechaOperacion = (TextView) finder.findRequiredView(obj, R.id.F32_15_LBL_DATA_FechaOperacion, "field 'lblFechaOperacion'");
        nuevoDebinActivity.lblLeyenda = (TextView) finder.findRequiredView(obj, R.id.F32_15_LBL_DATA_Leyenda, "field 'lblLeyenda'");
        nuevoDebinActivity.lblNroComprobante = (TextView) finder.findRequiredView(obj, R.id.F32_15_LBL_DATA_nroComprobante, "field 'lblNroComprobante'");
        nuevoDebinActivity.btnVolver = (Button) finder.findRequiredView(obj, R.id.F32_15_btn_volver, "field 'btnVolver'");
        nuevoDebinActivity.comprobanteDebin = (ScrollView) finder.findRequiredView(obj, R.id.F32_15_comprobanteGeneracionDebin, "field 'comprobanteDebin'");
        nuevoDebinActivity.lblCompradorComp = (TextView) finder.findRequiredView(obj, R.id.F32_15_comprador, "field 'lblCompradorComp'");
        nuevoDebinActivity.lblCuitComp = (TextView) finder.findRequiredView(obj, R.id.F32_15_LBL_CUIT, "field 'lblCuitComp'");
        nuevoDebinActivity.lblAliasComp = (TextView) finder.findRequiredView(obj, R.id.F32_15_LBL_DATA_ALIAS, "field 'lblAliasComp'");
        nuevoDebinActivity.lblBancoComp = (TextView) finder.findRequiredView(obj, R.id.F32_15_LBL_DATA_BANCO, "field 'lblBancoComp'");
        nuevoDebinActivity.lblCBUComp = (TextView) finder.findRequiredView(obj, R.id.F32_15_LBL_DATA_CBU, "field 'lblCBUComp'");
        nuevoDebinActivity.lblConceptoComp = (TextView) finder.findRequiredView(obj, R.id.F32_15_LBL_DATA_CONCEPTO, "field 'lblConceptoComp'");
        nuevoDebinActivity.lblDescripcionComp = (TextView) finder.findRequiredView(obj, R.id.F32_15_LBL_DATA_DESCRIPCION, "field 'lblDescripcionComp'");
        nuevoDebinActivity.lblIdDebinDataComp = (TextView) finder.findRequiredView(obj, R.id.F32_15_LBL_DATA_idDebin, "field 'lblIdDebinDataComp'");
        nuevoDebinActivity.lblCtaAcreditacionComp = (TextView) finder.findRequiredView(obj, R.id.F32_15_LBL_DATA_CTA_ACREDITACION, "field 'lblCtaAcreditacionComp'");
        nuevoDebinActivity.lblFechaVtoComp = (TextView) finder.findRequiredView(obj, R.id.F32_15_LBL_DATA_FECHA_VENCIMIENTO, "field 'lblFechaVtoComp'");
        nuevoDebinActivity.etImporteComp = (TextView) finder.findRequiredView(obj, R.id.F32_15_importe, "field 'etImporteComp'");
        nuevoDebinActivity.rowAliasComp = (LinearLayout) finder.findRequiredView(obj, R.id.F32_15_row_alias, "field 'rowAliasComp'");
        nuevoDebinActivity.rowDescripcionComp = (LinearLayout) finder.findRequiredView(obj, R.id.F32_15_row_descripcion, "field 'rowDescripcionComp'");
        nuevoDebinActivity.rowidDebinComp = (LinearLayout) finder.findRequiredView(obj, R.id.F32_15_row_idDebin, "field 'rowidDebinComp'");
        nuevoDebinActivity.rowCBUComp = (LinearLayout) finder.findRequiredView(obj, R.id.F32_15_row_cbu, "field 'rowCBUComp'");
        nuevoDebinActivity.rowBancoComp = (LinearLayout) finder.findRequiredView(obj, R.id.F32_15_row_banco, "field 'rowBancoComp'");
        nuevoDebinActivity.lblRes4Msj = (TextView) finder.findRequiredView(obj, R.id.F32_16_txt_msj, "field 'lblRes4Msj'");
        nuevoDebinActivity.btnAdherirDebin = (Button) finder.findRequiredView(obj, R.id.F32_16_adherir_cuenta, "field 'btnAdherirDebin'");
        nuevoDebinActivity.cbuEE = (TextView) finder.findRequiredView(obj, R.id.F32_15_TXT_CBU, "field 'cbuEE'");
        nuevoDebinActivity.fvtoEE = (TextView) finder.findRequiredView(obj, R.id.F32_15_TXT_FECHA_VENCIMIENTO, "field 'fvtoEE'");
        nuevoDebinActivity.comproEE = (TextView) finder.findRequiredView(obj, R.id.F32_15_TXT_nroComprobante, "field 'comproEE'");
        nuevoDebinActivity.cuitEE = (TextView) finder.findRequiredView(obj, R.id.F32_15_TXT_CUIT, "field 'cuitEE'");
        nuevoDebinActivity.titleEE = (TextView) finder.findRequiredView(obj, R.id.F32_15_txt_title, "field 'titleEE'");
    }

    public static void reset(NuevoDebinActivity nuevoDebinActivity) {
        nuevoDebinActivity.mControlPager = null;
        nuevoDebinActivity.layout_sinCuentas = null;
        nuevoDebinActivity.txtSeleccionCBU = null;
        nuevoDebinActivity.imgDestinoSeleccionado = null;
        nuevoDebinActivity.txtAyuda = null;
        nuevoDebinActivity.btnVerificar = null;
        nuevoDebinActivity.selectorCBU = null;
        nuevoDebinActivity.etCBU = null;
        nuevoDebinActivity.lblTitle = null;
        nuevoDebinActivity.lblGenerarDebinTitle = null;
        nuevoDebinActivity.lblComprador = null;
        nuevoDebinActivity.lblCuit = null;
        nuevoDebinActivity.lblAlias = null;
        nuevoDebinActivity.lblBanco = null;
        nuevoDebinActivity.lblCBU = null;
        nuevoDebinActivity.lblConcepto = null;
        nuevoDebinActivity.lblDescripcion = null;
        nuevoDebinActivity.lblCtaAcreditacion = null;
        nuevoDebinActivity.lblFechaVto = null;
        nuevoDebinActivity.etImporte = null;
        nuevoDebinActivity.rowAlias = null;
        nuevoDebinActivity.btnContinuar = null;
        nuevoDebinActivity.rowCBU = null;
        nuevoDebinActivity.rowBanco = null;
        nuevoDebinActivity.leyendaGenerarDebin = null;
        nuevoDebinActivity.lblConfirmarTitle = null;
        nuevoDebinActivity.lblCompradorC = null;
        nuevoDebinActivity.lblCuitC = null;
        nuevoDebinActivity.lblAliasC = null;
        nuevoDebinActivity.lblBancoC = null;
        nuevoDebinActivity.lblCBUC = null;
        nuevoDebinActivity.lblConceptoC = null;
        nuevoDebinActivity.lblDescripcionC = null;
        nuevoDebinActivity.lblCtaAcreditacionC = null;
        nuevoDebinActivity.lblFechaVtoC = null;
        nuevoDebinActivity.etImporteC = null;
        nuevoDebinActivity.rowAliasC = null;
        nuevoDebinActivity.btnConfirmar = null;
        nuevoDebinActivity.rowDescripcion = null;
        nuevoDebinActivity.rowCBUC = null;
        nuevoDebinActivity.rowBancoC = null;
        nuevoDebinActivity.leyendaConfirmarDebin = null;
        nuevoDebinActivity.row_fechaOperacion = null;
        nuevoDebinActivity.row_nroComprobante = null;
        nuevoDebinActivity.lblFechaOperacion = null;
        nuevoDebinActivity.lblLeyenda = null;
        nuevoDebinActivity.lblNroComprobante = null;
        nuevoDebinActivity.btnVolver = null;
        nuevoDebinActivity.comprobanteDebin = null;
        nuevoDebinActivity.lblCompradorComp = null;
        nuevoDebinActivity.lblCuitComp = null;
        nuevoDebinActivity.lblAliasComp = null;
        nuevoDebinActivity.lblBancoComp = null;
        nuevoDebinActivity.lblCBUComp = null;
        nuevoDebinActivity.lblConceptoComp = null;
        nuevoDebinActivity.lblDescripcionComp = null;
        nuevoDebinActivity.lblIdDebinDataComp = null;
        nuevoDebinActivity.lblCtaAcreditacionComp = null;
        nuevoDebinActivity.lblFechaVtoComp = null;
        nuevoDebinActivity.etImporteComp = null;
        nuevoDebinActivity.rowAliasComp = null;
        nuevoDebinActivity.rowDescripcionComp = null;
        nuevoDebinActivity.rowidDebinComp = null;
        nuevoDebinActivity.rowCBUComp = null;
        nuevoDebinActivity.rowBancoComp = null;
        nuevoDebinActivity.lblRes4Msj = null;
        nuevoDebinActivity.btnAdherirDebin = null;
        nuevoDebinActivity.cbuEE = null;
        nuevoDebinActivity.fvtoEE = null;
        nuevoDebinActivity.comproEE = null;
        nuevoDebinActivity.cuitEE = null;
        nuevoDebinActivity.titleEE = null;
    }
}
