package ar.com.santander.rio.mbanking.app.ui.activities;

import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.ViewFlipper;
import ar.com.santander.rio.mbanking.R;
import ar.com.santander.rio.mbanking.view.HorizontalScrollList;
import butterknife.ButterKnife.Finder;

public class NuevoDestinatarioTransferenciaActivity$$ViewInjector {
    public static void inject(Finder finder, NuevoDestinatarioTransferenciaActivity nuevoDestinatarioTransferenciaActivity, Object obj) {
        nuevoDestinatarioTransferenciaActivity.mControlPager = (ViewFlipper) finder.findRequiredView(obj, R.id.nuevo_destinatario_view_flipper, "field 'mControlPager'");
        nuevoDestinatarioTransferenciaActivity.tabSelector = (HorizontalScrollList) finder.findRequiredView(obj, R.id.F23_05_HSL_SELECTOR_TAB, "field 'tabSelector'");
        nuevoDestinatarioTransferenciaActivity.nuevoDestinatarioPorCBU = (LinearLayout) finder.findRequiredView(obj, R.id.F23_05_LNL_NUEVO_DESTINATARIO_CBU, "field 'nuevoDestinatarioPorCBU'");
        nuevoDestinatarioTransferenciaActivity.nuevoDestinatarioPorCuentaBSR = (LinearLayout) finder.findRequiredView(obj, R.id.F23_05_LNL_NUEVO_DESTINATARIO_TERCEROS_BSR, "field 'nuevoDestinatarioPorCuentaBSR'");
        nuevoDestinatarioTransferenciaActivity.cEditTextNuevoDest = (EditText) finder.findRequiredView(obj, R.id.F23_05_INP_NUEVO_DESTINATARIO, "field 'cEditTextNuevoDest'");
        nuevoDestinatarioTransferenciaActivity.lblInputHint = (TextView) finder.findRequiredView(obj, R.id.F23_05_LBL_INPUT_HINT, "field 'lblInputHint'");
        nuevoDestinatarioTransferenciaActivity.lnlSelectorTipoAlta = (LinearLayout) finder.findRequiredView(obj, R.id.F23_05_LNL_SELECTOR_TIPO_ALTA, "field 'lnlSelectorTipoAlta'");
        nuevoDestinatarioTransferenciaActivity.lblSelectorTipoAlta = (TextView) finder.findRequiredView(obj, R.id.F23_05_LBL_TIPO_ALTA, "field 'lblSelectorTipoAlta'");
        nuevoDestinatarioTransferenciaActivity.inputTercerosBSR1 = (EditText) finder.findRequiredView(obj, R.id.F23_05_INP_NUEVO_DESTINATARIO_TERCEROS_BSR_1, "field 'inputTercerosBSR1'");
        nuevoDestinatarioTransferenciaActivity.inputTercerosBSR2 = (EditText) finder.findRequiredView(obj, R.id.F23_05_INP_NUEVO_DESTINATARIO_TERCEROS_BSR_2, "field 'inputTercerosBSR2'");
        nuevoDestinatarioTransferenciaActivity.inputTercerosBSR3 = (EditText) finder.findRequiredView(obj, R.id.F23_05_INP_NUEVO_DESTINATARIO_TERCEROS_BSR_3, "field 'inputTercerosBSR3'");
        nuevoDestinatarioTransferenciaActivity.lnlSelectorCuenta = (LinearLayout) finder.findRequiredView(obj, R.id.F23_05_LNL_SELECTOR_TIPO_CUENTA, "field 'lnlSelectorCuenta'");
        nuevoDestinatarioTransferenciaActivity.txtTipoCuenta = (TextView) finder.findRequiredView(obj, R.id.F23_05_LBL_DATA_TIPO_CUENTA, "field 'txtTipoCuenta'");
        nuevoDestinatarioTransferenciaActivity.textViewAlertInvalidCBU = (TextView) finder.findRequiredView(obj, R.id.F23_05_LBL_INPUT_INVALIDO, "field 'textViewAlertInvalidCBU'");
        nuevoDestinatarioTransferenciaActivity.btnClearFields = (Button) finder.findRequiredView(obj, R.id.F23_05_BTN_CLEAR_FIELDS, "field 'btnClearFields'");
        nuevoDestinatarioTransferenciaActivity.btnVerificar = (Button) finder.findRequiredView(obj, R.id.F23_05_BTN_VERIFICAR, "field 'btnVerificar'");
        nuevoDestinatarioTransferenciaActivity.btnContinuarSinVerificar = (Button) finder.findRequiredView(obj, R.id.F23_05_BTN_CONTINUAR_SIN_VERIFICAR, "field 'btnContinuarSinVerificar'");
        nuevoDestinatarioTransferenciaActivity.txtCBUAltaManual = (TextView) finder.findRequiredView(obj, R.id.F23_06_LBL_DATA_CBU, "field 'txtCBUAltaManual'");
        nuevoDestinatarioTransferenciaActivity.editTextTitularAltaManual = (EditText) finder.findRequiredView(obj, R.id.F23_06_INP_TITULAR, "field 'editTextTitularAltaManual'");
        nuevoDestinatarioTransferenciaActivity.editTextCUITAltaManual = (EditText) finder.findRequiredView(obj, R.id.F23_06_INP_CUIT_CUIL, "field 'editTextCUITAltaManual'");
        nuevoDestinatarioTransferenciaActivity.editTextBancoAltaManual = (EditText) finder.findRequiredView(obj, R.id.F23_06_INP_BANCO, "field 'editTextBancoAltaManual'");
        nuevoDestinatarioTransferenciaActivity.editTextRecordatorioAltaManual = (EditText) finder.findRequiredView(obj, R.id.F23_06_INP_RECORDATORIO, "field 'editTextRecordatorioAltaManual'");
        nuevoDestinatarioTransferenciaActivity.editTextEmailAltaManual = (EditText) finder.findRequiredView(obj, R.id.F23_06_INP_EMAIL, "field 'editTextEmailAltaManual'");
        nuevoDestinatarioTransferenciaActivity.btnGuardarAltaManual = (Button) finder.findRequiredView(obj, R.id.F23_06_BTN_GUARDAR, "field 'btnGuardarAltaManual'");
        nuevoDestinatarioTransferenciaActivity.txtTitleVerificar = (TextView) finder.findRequiredView(obj, R.id.F23_20_LBL_TITLE, "field 'txtTitleVerificar'");
        nuevoDestinatarioTransferenciaActivity.lblAliasVerificar = (TextView) finder.findRequiredView(obj, R.id.F23_20_LBL_ALIAS, "field 'lblAliasVerificar'");
        nuevoDestinatarioTransferenciaActivity.txtAliasVerificar = (TextView) finder.findRequiredView(obj, R.id.F23_20_LBL_DATA_ALIAS, "field 'txtAliasVerificar'");
        nuevoDestinatarioTransferenciaActivity.txtTitularVerificar = (TextView) finder.findRequiredView(obj, R.id.F23_20_LBL_DATA_TITULAR, "field 'txtTitularVerificar'");
        nuevoDestinatarioTransferenciaActivity.lblCUITHeaderVerificar = (TextView) finder.findRequiredView(obj, R.id.F23_20_LBL_CUIT_CUIL_HEADER, "field 'lblCUITHeaderVerificar'");
        nuevoDestinatarioTransferenciaActivity.txtCUITHeaderVerificar = (TextView) finder.findRequiredView(obj, R.id.F23_20_LBL_DATA_CUIT_CUIL_HEADER, "field 'txtCUITHeaderVerificar'");
        nuevoDestinatarioTransferenciaActivity.rowCBUVerificar = (LinearLayout) finder.findRequiredView(obj, R.id.F23_20_LNL_ROW_CBU, "field 'rowCBUVerificar'");
        nuevoDestinatarioTransferenciaActivity.txtCBUVerificar = (TextView) finder.findRequiredView(obj, R.id.F23_20_LBL_DATA_CBU, "field 'txtCBUVerificar'");
        nuevoDestinatarioTransferenciaActivity.rowCUITVerificar = (LinearLayout) finder.findRequiredView(obj, R.id.F23_20_LNL_ROW_CUIT, "field 'rowCUITVerificar'");
        nuevoDestinatarioTransferenciaActivity.txtCUITVerificar = (TextView) finder.findRequiredView(obj, R.id.F23_20_LBL_DATA_CUIT, "field 'txtCUITVerificar'");
        nuevoDestinatarioTransferenciaActivity.txtBancoVerificar = (TextView) finder.findRequiredView(obj, R.id.F23_20_LBL_DATA_BANCO, "field 'txtBancoVerificar'");
        nuevoDestinatarioTransferenciaActivity.rowTipoCuentaVerificar = (LinearLayout) finder.findRequiredView(obj, R.id.F23_20_LNL_ROW_TIPO_CUENTA, "field 'rowTipoCuentaVerificar'");
        nuevoDestinatarioTransferenciaActivity.lblTipoCuentaVerificar = (TextView) finder.findRequiredView(obj, R.id.F23_20_LBL_TIPO_CUENTA, "field 'lblTipoCuentaVerificar'");
        nuevoDestinatarioTransferenciaActivity.txtTipoCuentaVerificar = (TextView) finder.findRequiredView(obj, R.id.F23_20_LBL_DATA_TIPO_CUENTA, "field 'txtTipoCuentaVerificar'");
        nuevoDestinatarioTransferenciaActivity.rowNumeroCuentaVerificar = (LinearLayout) finder.findRequiredView(obj, R.id.F23_20_LNL_ROW_NUMERO_CUENTA, "field 'rowNumeroCuentaVerificar'");
        nuevoDestinatarioTransferenciaActivity.txtNumeroCuentaVerificar = (TextView) finder.findRequiredView(obj, R.id.F23_20_LBL_DATA_NUMERO_CUENTA, "field 'txtNumeroCuentaVerificar'");
        nuevoDestinatarioTransferenciaActivity.editTextRecordatorioVerificar = (EditText) finder.findRequiredView(obj, R.id.F23_20_INP_RECORDATORIO, "field 'editTextRecordatorioVerificar'");
        nuevoDestinatarioTransferenciaActivity.editTextEmailVerificar = (EditText) finder.findRequiredView(obj, R.id.F23_20_INP_EMAIL, "field 'editTextEmailVerificar'");
        nuevoDestinatarioTransferenciaActivity.btnContinuarPantallaVerificar = (Button) finder.findRequiredView(obj, R.id.F23_20_BTN_CONTINUAR, "field 'btnContinuarPantallaVerificar'");
        nuevoDestinatarioTransferenciaActivity.txtTitleConfirmar = (TextView) finder.findRequiredView(obj, R.id.F23_21_LBL_TITLE, "field 'txtTitleConfirmar'");
        nuevoDestinatarioTransferenciaActivity.tableLayoutConfirmar = (TableLayout) finder.findRequiredView(obj, R.id.F23_21_TABLE, "field 'tableLayoutConfirmar'");
        nuevoDestinatarioTransferenciaActivity.btnGuardarConfirmar = (TextView) finder.findRequiredView(obj, R.id.F23_21_BTN_GUARDAR, "field 'btnGuardarConfirmar'");
        nuevoDestinatarioTransferenciaActivity.tableLayoutComprobante = (TableLayout) finder.findRequiredView(obj, R.id.F23_04_TABLE, "field 'tableLayoutComprobante'");
        nuevoDestinatarioTransferenciaActivity.btnTransferir = (Button) finder.findRequiredView(obj, R.id.F23_04_BTN_TRANSFERIR, "field 'btnTransferir'");
        nuevoDestinatarioTransferenciaActivity.btnAgenda = (Button) finder.findRequiredView(obj, R.id.F23_04_BTN_AGENDA, "field 'btnAgenda'");
        nuevoDestinatarioTransferenciaActivity.comprobanteOperacion = (ScrollView) finder.findRequiredView(obj, R.id.F23_04_SCR_COMPROBANTE, "field 'comprobanteOperacion'");
    }

    public static void reset(NuevoDestinatarioTransferenciaActivity nuevoDestinatarioTransferenciaActivity) {
        nuevoDestinatarioTransferenciaActivity.mControlPager = null;
        nuevoDestinatarioTransferenciaActivity.tabSelector = null;
        nuevoDestinatarioTransferenciaActivity.nuevoDestinatarioPorCBU = null;
        nuevoDestinatarioTransferenciaActivity.nuevoDestinatarioPorCuentaBSR = null;
        nuevoDestinatarioTransferenciaActivity.cEditTextNuevoDest = null;
        nuevoDestinatarioTransferenciaActivity.lblInputHint = null;
        nuevoDestinatarioTransferenciaActivity.lnlSelectorTipoAlta = null;
        nuevoDestinatarioTransferenciaActivity.lblSelectorTipoAlta = null;
        nuevoDestinatarioTransferenciaActivity.inputTercerosBSR1 = null;
        nuevoDestinatarioTransferenciaActivity.inputTercerosBSR2 = null;
        nuevoDestinatarioTransferenciaActivity.inputTercerosBSR3 = null;
        nuevoDestinatarioTransferenciaActivity.lnlSelectorCuenta = null;
        nuevoDestinatarioTransferenciaActivity.txtTipoCuenta = null;
        nuevoDestinatarioTransferenciaActivity.textViewAlertInvalidCBU = null;
        nuevoDestinatarioTransferenciaActivity.btnClearFields = null;
        nuevoDestinatarioTransferenciaActivity.btnVerificar = null;
        nuevoDestinatarioTransferenciaActivity.btnContinuarSinVerificar = null;
        nuevoDestinatarioTransferenciaActivity.txtCBUAltaManual = null;
        nuevoDestinatarioTransferenciaActivity.editTextTitularAltaManual = null;
        nuevoDestinatarioTransferenciaActivity.editTextCUITAltaManual = null;
        nuevoDestinatarioTransferenciaActivity.editTextBancoAltaManual = null;
        nuevoDestinatarioTransferenciaActivity.editTextRecordatorioAltaManual = null;
        nuevoDestinatarioTransferenciaActivity.editTextEmailAltaManual = null;
        nuevoDestinatarioTransferenciaActivity.btnGuardarAltaManual = null;
        nuevoDestinatarioTransferenciaActivity.txtTitleVerificar = null;
        nuevoDestinatarioTransferenciaActivity.lblAliasVerificar = null;
        nuevoDestinatarioTransferenciaActivity.txtAliasVerificar = null;
        nuevoDestinatarioTransferenciaActivity.txtTitularVerificar = null;
        nuevoDestinatarioTransferenciaActivity.lblCUITHeaderVerificar = null;
        nuevoDestinatarioTransferenciaActivity.txtCUITHeaderVerificar = null;
        nuevoDestinatarioTransferenciaActivity.rowCBUVerificar = null;
        nuevoDestinatarioTransferenciaActivity.txtCBUVerificar = null;
        nuevoDestinatarioTransferenciaActivity.rowCUITVerificar = null;
        nuevoDestinatarioTransferenciaActivity.txtCUITVerificar = null;
        nuevoDestinatarioTransferenciaActivity.txtBancoVerificar = null;
        nuevoDestinatarioTransferenciaActivity.rowTipoCuentaVerificar = null;
        nuevoDestinatarioTransferenciaActivity.lblTipoCuentaVerificar = null;
        nuevoDestinatarioTransferenciaActivity.txtTipoCuentaVerificar = null;
        nuevoDestinatarioTransferenciaActivity.rowNumeroCuentaVerificar = null;
        nuevoDestinatarioTransferenciaActivity.txtNumeroCuentaVerificar = null;
        nuevoDestinatarioTransferenciaActivity.editTextRecordatorioVerificar = null;
        nuevoDestinatarioTransferenciaActivity.editTextEmailVerificar = null;
        nuevoDestinatarioTransferenciaActivity.btnContinuarPantallaVerificar = null;
        nuevoDestinatarioTransferenciaActivity.txtTitleConfirmar = null;
        nuevoDestinatarioTransferenciaActivity.tableLayoutConfirmar = null;
        nuevoDestinatarioTransferenciaActivity.btnGuardarConfirmar = null;
        nuevoDestinatarioTransferenciaActivity.tableLayoutComprobante = null;
        nuevoDestinatarioTransferenciaActivity.btnTransferir = null;
        nuevoDestinatarioTransferenciaActivity.btnAgenda = null;
        nuevoDestinatarioTransferenciaActivity.comprobanteOperacion = null;
    }
}
