package ar.com.santander.rio.mbanking.app.ui.activities;

import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.ViewFlipper;
import ar.com.santander.rio.mbanking.R;
import ar.com.santander.rio.mbanking.view.CustomSpinner;
import ar.com.santander.rio.mbanking.view.NumericEditTextWithPrefixAccesibility;
import butterknife.ButterKnife.Finder;

public class RescatarFondoActivity$$ViewInjector {
    public static void inject(Finder finder, RescatarFondoActivity rescatarFondoActivity, Object obj) {
        rescatarFondoActivity.mControlPager = (ViewFlipper) finder.findRequiredView(obj, R.id.fondos_rescatar_view_flipper, "field 'mControlPager'");
        rescatarFondoActivity.rllSelectedAmountType = (RelativeLayout) finder.findRequiredView(obj, R.id.F24_20_RLL_SELECTED_AMOUNT_TYPE, "field 'rllSelectedAmountType'");
        rescatarFondoActivity.vgSelectorAccount = (CustomSpinner) finder.findRequiredView(obj, R.id.F24_20_vgSelectorAccount, "field 'vgSelectorAccount'");
        rescatarFondoActivity.lblDataCuentaTitulo = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_data_cuentaTitulo, "field 'lblDataCuentaTitulo'");
        rescatarFondoActivity.lblSelectedAmountType = (TextView) finder.findRequiredView(obj, R.id.F24_20_LBL_SELECTED_AMOUNT_TYPE, "field 'lblSelectedAmountType'");
        rescatarFondoActivity.inpAmount = (NumericEditTextWithPrefixAccesibility) finder.findRequiredView(obj, R.id.F24_20_INP_AMOUNT, "field 'inpAmount'");
        rescatarFondoActivity.lblDataFondo = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_data_fondo, "field 'lblDataFondo'");
        rescatarFondoActivity.lblDataImporteTotal = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_data_importeTotal, "field 'lblDataImporteTotal'");
        rescatarFondoActivity.lblDataCuotapartes = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_data_cuotaPartes, "field 'lblDataCuotapartes'");
        rescatarFondoActivity.lblDataValorCuotapartes = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_data_valorCuotaparte, "field 'lblDataValorCuotapartes'");
        rescatarFondoActivity.rowPlazoPago = (LinearLayout) finder.findRequiredView(obj, R.id.F24_20_row_plazoPago, "field 'rowPlazoPago'");
        rescatarFondoActivity.lblDataPlazoPago = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_data_plazoPago, "field 'lblDataPlazoPago'");
        rescatarFondoActivity.btnContinuar = (Button) finder.findRequiredView(obj, R.id.F24_20_btn_continuar, "field 'btnContinuar'");
        rescatarFondoActivity.rowCuentaTituloRescatar = (LinearLayout) finder.findRequiredView(obj, R.id.F24_20_row_cuentaTitulo_bottom, "field 'rowCuentaTituloRescatar'");
        rescatarFondoActivity.rowOrigenRescatar = (LinearLayout) finder.findRequiredView(obj, R.id.F24_20_row_origen, "field 'rowOrigenRescatar'");
        rescatarFondoActivity.lblDestino = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_origen, "field 'lblDestino'");
        rescatarFondoActivity.lblDataDestino = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_data_origen, "field 'lblDataDestino'");
        rescatarFondoActivity.rowCuotapartes = (LinearLayout) finder.findRequiredView(obj, R.id.F24_20_row_cuotaPartes, "field 'rowCuotapartes'");
        rescatarFondoActivity.rowValorCuotapartes = (LinearLayout) finder.findRequiredView(obj, R.id.F24_20_row_valorCuotaparte, "field 'rowValorCuotapartes'");
        rescatarFondoActivity.lblDataConfirmarFondoRescatar = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_fondoRescatar, "field 'lblDataConfirmarFondoRescatar'");
        rescatarFondoActivity.lblDataConfirmarImporte = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_importe, "field 'lblDataConfirmarImporte'");
        rescatarFondoActivity.lblDataConfirmarCuotaparte = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_cuotaparte, "field 'lblDataConfirmarCuotaparte'");
        rescatarFondoActivity.lblDataConfirmarValorCuotaparte = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_valorCuotaParte, "field 'lblDataConfirmarValorCuotaparte'");
        rescatarFondoActivity.lblDataConfirmarCuentaTitulo = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_cuentaTitulo, "field 'lblDataConfirmarCuentaTitulo'");
        rescatarFondoActivity.lblDataConfirmarFondo = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_fondo, "field 'lblDataConfirmarFondo'");
        rescatarFondoActivity.lblDataConfirmarCuentaDestino = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_cuentaDestino, "field 'lblDataConfirmarCuentaDestino'");
        rescatarFondoActivity.lblDataConfirmarPlazoPago = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_plazoPago, "field 'lblDataConfirmarPlazoPago'");
        rescatarFondoActivity.imgCheckboxTyC = (ImageView) finder.findRequiredView(obj, R.id.F24_21_img_checkbox_tyc, "field 'imgCheckboxTyC'");
        rescatarFondoActivity.lblConectorVerTyC = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_conectorVerTerminos, "field 'lblConectorVerTyC'");
        rescatarFondoActivity.lblVerTyC = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_verTerminos, "field 'lblVerTyC'");
        rescatarFondoActivity.lblConfirmarTerminosLegales = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_terminosLegales, "field 'lblConfirmarTerminosLegales'");
        rescatarFondoActivity.btnConfirmar = (Button) finder.findRequiredView(obj, R.id.F24_21_btn_confirmar, "field 'btnConfirmar'");
        rescatarFondoActivity.rlTerminosyCondiciones = (RelativeLayout) finder.findRequiredView(obj, R.id.F24_21_rll_terminosCondiciones, "field 'rlTerminosyCondiciones'");
        rescatarFondoActivity.rowPlazoDePago = (LinearLayout) finder.findRequiredView(obj, R.id.F24_21_row_plazoPago, "field 'rowPlazoDePago'");
        rescatarFondoActivity.rowValorCuotapartesBottomConfirmar = finder.findRequiredView(obj, R.id.F24_21_row_valorCuotaparteConfirmar, "field 'rowValorCuotapartesBottomConfirmar'");
        rescatarFondoActivity.lblFueraHorarioMensaje = (TextView) finder.findRequiredView(obj, R.id.FXX_XX_LBL_MESSAGE, "field 'lblFueraHorarioMensaje'");
        rescatarFondoActivity.comprobanteOperacion = (ScrollView) finder.findRequiredView(obj, R.id.F24_22_scrollViewComprobante, "field 'comprobanteOperacion'");
        rescatarFondoActivity.lblDataComprobanteFondoRescatar = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_fondoRescatar, "field 'lblDataComprobanteFondoRescatar'");
        rescatarFondoActivity.lblDataComprobanteImporte = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_importeHeader, "field 'lblDataComprobanteImporte'");
        rescatarFondoActivity.lblDataComprobanteCuotaparte = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_cuotaparteHeader, "field 'lblDataComprobanteCuotaparte'");
        rescatarFondoActivity.lblDataComprobanteValorCuotaparte = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_valorCuotaparteHeader, "field 'lblDataComprobanteValorCuotaparte'");
        rescatarFondoActivity.lblDataComprobanteFechaHora = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_fechaHora, "field 'lblDataComprobanteFechaHora'");
        rescatarFondoActivity.lblDataComprobanteCuentaTitulo = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_cuentaTitulo, "field 'lblDataComprobanteCuentaTitulo'");
        rescatarFondoActivity.lblDataComprobanteFondo = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_fondo, "field 'lblDataComprobanteFondo'");
        rescatarFondoActivity.lblDataComprobanteCuentaDestino = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_cuentaDestino, "field 'lblDataComprobanteCuentaDestino'");
        rescatarFondoActivity.lblDataComprobanteImporteBottom = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_importeBottom, "field 'lblDataComprobanteImporteBottom'");
        rescatarFondoActivity.lblDataComprobanteValorCuotaparteBottom = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_valorCuotaparteBottom, "field 'lblDataComprobanteValorCuotaparteBottom'");
        rescatarFondoActivity.lblDataComprobanteCuotapartesBottom = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_cuotapartesBottom, "field 'lblDataComprobanteCuotapartesBottom'");
        rescatarFondoActivity.lblCertificadoComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_certificado, "field 'lblCertificadoComprobante'");
        rescatarFondoActivity.lblDataComprobanteCertificado = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_certificado, "field 'lblDataComprobanteCertificado'");
        rescatarFondoActivity.lblComprobanteTerminosLegales = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_terminosLegales, "field 'lblComprobanteTerminosLegales'");
        rescatarFondoActivity.btnVolver = (Button) finder.findRequiredView(obj, R.id.F24_22_btn_volver, "field 'btnVolver'");
        rescatarFondoActivity.rowCuentaDebitoComprobante = (LinearLayout) finder.findRequiredView(obj, R.id.F24_22_row_cuenta_Debito, "field 'rowCuentaDebitoComprobante'");
        rescatarFondoActivity.lblDataPlazodePago = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_plazo_de_pago, "field 'lblDataPlazodePago'");
        rescatarFondoActivity.rowPlazoPagoComprobante = (LinearLayout) finder.findRequiredView(obj, R.id.F24_22_row_plazo_de_pago, "field 'rowPlazoPagoComprobante'");
        rescatarFondoActivity.rowValorCuotaparteComprobante = (LinearLayout) finder.findRequiredView(obj, R.id.F24_22_row_valorCuotaparteBottom, "field 'rowValorCuotaparteComprobante'");
        rescatarFondoActivity.rowImporteTop = (LinearLayout) finder.findRequiredView(obj, R.id.rowImporteTop, "field 'rowImporteTop'");
        rescatarFondoActivity.rowValorCuotapartesTop = (LinearLayout) finder.findRequiredView(obj, R.id.rowValorCuotapartes, "field 'rowValorCuotapartesTop'");
        rescatarFondoActivity.rowLinearFondo = (LinearLayout) finder.findRequiredView(obj, R.id.F24_22_row_fondo, "field 'rowLinearFondo'");
        rescatarFondoActivity.rowLinearCuentaDestino = (LinearLayout) finder.findRequiredView(obj, R.id.F24_22_row_cuentaDestino, "field 'rowLinearCuentaDestino'");
    }

    public static void reset(RescatarFondoActivity rescatarFondoActivity) {
        rescatarFondoActivity.mControlPager = null;
        rescatarFondoActivity.rllSelectedAmountType = null;
        rescatarFondoActivity.vgSelectorAccount = null;
        rescatarFondoActivity.lblDataCuentaTitulo = null;
        rescatarFondoActivity.lblSelectedAmountType = null;
        rescatarFondoActivity.inpAmount = null;
        rescatarFondoActivity.lblDataFondo = null;
        rescatarFondoActivity.lblDataImporteTotal = null;
        rescatarFondoActivity.lblDataCuotapartes = null;
        rescatarFondoActivity.lblDataValorCuotapartes = null;
        rescatarFondoActivity.rowPlazoPago = null;
        rescatarFondoActivity.lblDataPlazoPago = null;
        rescatarFondoActivity.btnContinuar = null;
        rescatarFondoActivity.rowCuentaTituloRescatar = null;
        rescatarFondoActivity.rowOrigenRescatar = null;
        rescatarFondoActivity.lblDestino = null;
        rescatarFondoActivity.lblDataDestino = null;
        rescatarFondoActivity.rowCuotapartes = null;
        rescatarFondoActivity.rowValorCuotapartes = null;
        rescatarFondoActivity.lblDataConfirmarFondoRescatar = null;
        rescatarFondoActivity.lblDataConfirmarImporte = null;
        rescatarFondoActivity.lblDataConfirmarCuotaparte = null;
        rescatarFondoActivity.lblDataConfirmarValorCuotaparte = null;
        rescatarFondoActivity.lblDataConfirmarCuentaTitulo = null;
        rescatarFondoActivity.lblDataConfirmarFondo = null;
        rescatarFondoActivity.lblDataConfirmarCuentaDestino = null;
        rescatarFondoActivity.lblDataConfirmarPlazoPago = null;
        rescatarFondoActivity.imgCheckboxTyC = null;
        rescatarFondoActivity.lblConectorVerTyC = null;
        rescatarFondoActivity.lblVerTyC = null;
        rescatarFondoActivity.lblConfirmarTerminosLegales = null;
        rescatarFondoActivity.btnConfirmar = null;
        rescatarFondoActivity.rlTerminosyCondiciones = null;
        rescatarFondoActivity.rowPlazoDePago = null;
        rescatarFondoActivity.rowValorCuotapartesBottomConfirmar = null;
        rescatarFondoActivity.lblFueraHorarioMensaje = null;
        rescatarFondoActivity.comprobanteOperacion = null;
        rescatarFondoActivity.lblDataComprobanteFondoRescatar = null;
        rescatarFondoActivity.lblDataComprobanteImporte = null;
        rescatarFondoActivity.lblDataComprobanteCuotaparte = null;
        rescatarFondoActivity.lblDataComprobanteValorCuotaparte = null;
        rescatarFondoActivity.lblDataComprobanteFechaHora = null;
        rescatarFondoActivity.lblDataComprobanteCuentaTitulo = null;
        rescatarFondoActivity.lblDataComprobanteFondo = null;
        rescatarFondoActivity.lblDataComprobanteCuentaDestino = null;
        rescatarFondoActivity.lblDataComprobanteImporteBottom = null;
        rescatarFondoActivity.lblDataComprobanteValorCuotaparteBottom = null;
        rescatarFondoActivity.lblDataComprobanteCuotapartesBottom = null;
        rescatarFondoActivity.lblCertificadoComprobante = null;
        rescatarFondoActivity.lblDataComprobanteCertificado = null;
        rescatarFondoActivity.lblComprobanteTerminosLegales = null;
        rescatarFondoActivity.btnVolver = null;
        rescatarFondoActivity.rowCuentaDebitoComprobante = null;
        rescatarFondoActivity.lblDataPlazodePago = null;
        rescatarFondoActivity.rowPlazoPagoComprobante = null;
        rescatarFondoActivity.rowValorCuotaparteComprobante = null;
        rescatarFondoActivity.rowImporteTop = null;
        rescatarFondoActivity.rowValorCuotapartesTop = null;
        rescatarFondoActivity.rowLinearFondo = null;
        rescatarFondoActivity.rowLinearCuentaDestino = null;
    }
}
