package ar.com.santander.rio.mbanking.app.ui.activities;

import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.ViewFlipper;
import ar.com.santander.rio.mbanking.R;
import ar.com.santander.rio.mbanking.view.NumericEditTextWithPrefixAccesibility;
import butterknife.ButterKnife.Finder;

public class SolicitudAumentoActivity$$ViewInjector {
    public static void inject(Finder finder, SolicitudAumentoActivity solicitudAumentoActivity, Object obj) {
        solicitudAumentoActivity.mControlPager = (ViewFlipper) finder.findRequiredView(obj, R.id.solicitud_aumento_view_flipper, "field 'mControlPager'");
        solicitudAumentoActivity.boton_continuar = (Button) finder.findRequiredView(obj, R.id.F33_00_btn_continuar, "field 'boton_continuar'");
        solicitudAumentoActivity.linearLayoutDe = (LinearLayout) finder.findRequiredView(obj, R.id.linearLayoutDe, "field 'linearLayoutDe'");
        solicitudAumentoActivity.lnlParaDestinatarios = (LinearLayout) finder.findRequiredView(obj, R.id.linearLayoutPara, "field 'lnlParaDestinatarios'");
        solicitudAumentoActivity.selector_importe = (RelativeLayout) finder.findRequiredView(obj, R.id.selectorImporte, "field 'selector_importe'");
        solicitudAumentoActivity.texto_importe_en = (TextView) finder.findRequiredView(obj, R.id.txtimporteSeleccionado, "field 'texto_importe_en'");
        solicitudAumentoActivity.flecha_seleccion_importe = (ImageView) finder.findRequiredView(obj, R.id.imgImporteSeleccionado, "field 'flecha_seleccion_importe'");
        solicitudAumentoActivity.edit_text_mporte = (NumericEditTextWithPrefixAccesibility) finder.findRequiredView(obj, R.id.editTextImporte, "field 'edit_text_mporte'");
        solicitudAumentoActivity.texto_seleccionar = (TextView) finder.findRequiredView(obj, R.id.textViewSeleccionar, "field 'texto_seleccionar'");
        solicitudAumentoActivity.lbl_data_cuenta_origen = (TextView) finder.findRequiredView(obj, R.id.textViewCuentaOrigen, "field 'lbl_data_cuenta_origen'");
        solicitudAumentoActivity.lbl_data_fecha = (TextView) finder.findRequiredView(obj, R.id.textViewFechaEjecucion, "field 'lbl_data_fecha'");
        solicitudAumentoActivity.texto_leyenda_final = (TextView) finder.findRequiredView(obj, R.id.F33_01_txt_leyenda, "field 'texto_leyenda_final'");
        solicitudAumentoActivity.boton_enviar = (Button) finder.findRequiredView(obj, R.id.F33_01_btn_enviar, "field 'boton_enviar'");
        solicitudAumentoActivity.lnlTitularDividerSolicitud = (LinearLayout) finder.findRequiredView(obj, R.id.linearLayoutTitularDividerSolicitud, "field 'lnlTitularDividerSolicitud'");
        solicitudAumentoActivity.lnlTitularSolicitud = (LinearLayout) finder.findRequiredView(obj, R.id.linearLayoutTitularSolicitud, "field 'lnlTitularSolicitud'");
        solicitudAumentoActivity.lnlTipoCuentaSolicitud = (LinearLayout) finder.findRequiredView(obj, R.id.linearLayoutTipoCuentaSolicitud, "field 'lnlTipoCuentaSolicitud'");
        solicitudAumentoActivity.lnlTipoSolicitud = (LinearLayout) finder.findRequiredView(obj, R.id.linearLayoutTipoSolicitud, "field 'lnlTipoSolicitud'");
        solicitudAumentoActivity.lnlNumeroSolicitud = (LinearLayout) finder.findRequiredView(obj, R.id.linearLayoutNumeroSolicitud, "field 'lnlNumeroSolicitud'");
        solicitudAumentoActivity.txtTitularSolicitud = (TextView) finder.findRequiredView(obj, R.id.textViewTitularSolicitud, "field 'txtTitularSolicitud'");
        solicitudAumentoActivity.txtAliasSolicitud = (TextView) finder.findRequiredView(obj, R.id.textViewAliasSolicitud, "field 'txtAliasSolicitud'");
        solicitudAumentoActivity.lnlAliasSolicitud = (LinearLayout) finder.findRequiredView(obj, R.id.linearLayoutAliasSolicitud, "field 'lnlAliasSolicitud'");
        solicitudAumentoActivity.txtTipoCuentaSolicitud = (TextView) finder.findRequiredView(obj, R.id.textViewTipoCuentaSolicitud, "field 'txtTipoCuentaSolicitud'");
        solicitudAumentoActivity.lnlCuitSolicitud = (LinearLayout) finder.findRequiredView(obj, R.id.linearLayoutCUITSolicitud, "field 'lnlCuitSolicitud'");
        solicitudAumentoActivity.lnlBancoDestinoSolicitud = (LinearLayout) finder.findRequiredView(obj, R.id.linearLayoutBancoDestinoSolicitud, "field 'lnlBancoDestinoSolicitud'");
        solicitudAumentoActivity.lnlCBUSolicitud = (LinearLayout) finder.findRequiredView(obj, R.id.linearLayoutCBUSolicitud, "field 'lnlCBUSolicitud'");
        solicitudAumentoActivity.txtTipoSolicitud = (TextView) finder.findRequiredView(obj, R.id.textViewTipoSolicitud, "field 'txtTipoSolicitud'");
        solicitudAumentoActivity.txtNumeroSolicitud = (TextView) finder.findRequiredView(obj, R.id.textViewNumeroSolicitud, "field 'txtNumeroSolicitud'");
        solicitudAumentoActivity.txtCBUSolicitud = (TextView) finder.findRequiredView(obj, R.id.textViewCBUSolicitud, "field 'txtCBUSolicitud'");
        solicitudAumentoActivity.txtBancoDestinoSolicitud = (TextView) finder.findRequiredView(obj, R.id.textViewBancoDestinoSolicitud, "field 'txtBancoDestinoSolicitud'");
        solicitudAumentoActivity.txtCuitSolicitud = (TextView) finder.findRequiredView(obj, R.id.textViewCUITSolicitud, "field 'txtCuitSolicitud'");
        solicitudAumentoActivity.data_importe = (TextView) finder.findRequiredView(obj, R.id.F33_02_lbl_data_importe_mensual, "field 'data_importe'");
        solicitudAumentoActivity.data_para = (TextView) finder.findRequiredView(obj, R.id.F33_02_LBL_DATA_PARA, "field 'data_para'");
        solicitudAumentoActivity.data_Titular = (TextView) finder.findRequiredView(obj, R.id.F33_02_LBL_DATA_TITULAR, "field 'data_Titular'");
        solicitudAumentoActivity.data_tipo_cuenta = (TextView) finder.findRequiredView(obj, R.id.F33_02_LBL_DATA_TIPO_CUENTA, "field 'data_tipo_cuenta'");
        solicitudAumentoActivity.data_row_tipo_cuenta = (LinearLayout) finder.findRequiredView(obj, R.id.F33_02_LNL_ROW_TIPO_CUENTA, "field 'data_row_tipo_cuenta'");
        solicitudAumentoActivity.data_banco_destino = (TextView) finder.findRequiredView(obj, R.id.F33_02_LBL_DATA_BANCO_DESTINO, "field 'data_banco_destino'");
        solicitudAumentoActivity.data_row_banco_destino = (LinearLayout) finder.findRequiredView(obj, R.id.F33_02_LNL_ROW_BANCO_DESTINO, "field 'data_row_banco_destino'");
        solicitudAumentoActivity.data_tipo = (TextView) finder.findRequiredView(obj, R.id.F33_02_LBL_DATA_TIPO, "field 'data_tipo'");
        solicitudAumentoActivity.data_numero = (TextView) finder.findRequiredView(obj, R.id.F33_02_LBL_DATA_NUMERO, "field 'data_numero'");
        solicitudAumentoActivity.data_de = (TextView) finder.findRequiredView(obj, R.id.F33_02_LBL_DATA_DE, "field 'data_de'");
        solicitudAumentoActivity.data_fecha = (TextView) finder.findRequiredView(obj, R.id.F33_02_LBL_DATA_FECHA, "field 'data_fecha'");
        solicitudAumentoActivity.data_leyenda = (TextView) finder.findRequiredView(obj, R.id.F33_02_txt_leyenda, "field 'data_leyenda'");
        solicitudAumentoActivity.btn_confirmar = (Button) finder.findRequiredView(obj, R.id.F33_02_btn_confirmar, "field 'btn_confirmar'");
        solicitudAumentoActivity.comprobante_data_importe = (TextView) finder.findRequiredView(obj, R.id.F33_03_lbl_data_importe_mensual, "field 'comprobante_data_importe'");
        solicitudAumentoActivity.comprobante_data_para = (TextView) finder.findRequiredView(obj, R.id.F33_03_LBL_DATA_PARA, "field 'comprobante_data_para'");
        solicitudAumentoActivity.comprobante_data_Titular = (TextView) finder.findRequiredView(obj, R.id.F33_03_LBL_DATA_TITULAR, "field 'comprobante_data_Titular'");
        solicitudAumentoActivity.comprobante_data_tipo_cuenta = (TextView) finder.findRequiredView(obj, R.id.F33_03_LBL_DATA_TIPO_CUENTA, "field 'comprobante_data_tipo_cuenta'");
        solicitudAumentoActivity.comprobante_data_row_tipo_cuenta = (LinearLayout) finder.findRequiredView(obj, R.id.F33_03_LNL_ROW_TIPO_CUENTA, "field 'comprobante_data_row_tipo_cuenta'");
        solicitudAumentoActivity.comprobante_data_row_banco_destino = (LinearLayout) finder.findRequiredView(obj, R.id.F33_03_LNL_ROW_BANCO_DESTINO, "field 'comprobante_data_row_banco_destino'");
        solicitudAumentoActivity.comprobante_data_banco_destino = (TextView) finder.findRequiredView(obj, R.id.F33_03_LBL_DATA_BANCO_DESTINO, "field 'comprobante_data_banco_destino'");
        solicitudAumentoActivity.comprobante_data_tipo = (TextView) finder.findRequiredView(obj, R.id.F33_03_LBL_DATA_TIPO, "field 'comprobante_data_tipo'");
        solicitudAumentoActivity.comprobante_data_numero = (TextView) finder.findRequiredView(obj, R.id.F33_03_LBL_DATA_NUMERO, "field 'comprobante_data_numero'");
        solicitudAumentoActivity.comprobante_data_de = (TextView) finder.findRequiredView(obj, R.id.F33_03_LBL_DATA_DE, "field 'comprobante_data_de'");
        solicitudAumentoActivity.comprobante_data_fecha = (TextView) finder.findRequiredView(obj, R.id.F33_03_LBL_DATA_FECHA, "field 'comprobante_data_fecha'");
        solicitudAumentoActivity.comprobante_data_nroComprobante = (TextView) finder.findRequiredView(obj, R.id.F33_03_LBL_DATA_NRO_COMPROBANTE, "field 'comprobante_data_nroComprobante'");
        solicitudAumentoActivity.btn_volver = (Button) finder.findRequiredView(obj, R.id.F33_03_btn_volver, "field 'btn_volver'");
        solicitudAumentoActivity.comprobanteSolicitud = (ScrollView) finder.findRequiredView(obj, R.id.comprobanteScrollView, "field 'comprobanteSolicitud'");
        solicitudAumentoActivity.data_leyenda_comprobante = (TextView) finder.findRequiredView(obj, R.id.F33_03_txt_leyenda, "field 'data_leyenda_comprobante'");
    }

    public static void reset(SolicitudAumentoActivity solicitudAumentoActivity) {
        solicitudAumentoActivity.mControlPager = null;
        solicitudAumentoActivity.boton_continuar = null;
        solicitudAumentoActivity.linearLayoutDe = null;
        solicitudAumentoActivity.lnlParaDestinatarios = null;
        solicitudAumentoActivity.selector_importe = null;
        solicitudAumentoActivity.texto_importe_en = null;
        solicitudAumentoActivity.flecha_seleccion_importe = null;
        solicitudAumentoActivity.edit_text_mporte = null;
        solicitudAumentoActivity.texto_seleccionar = null;
        solicitudAumentoActivity.lbl_data_cuenta_origen = null;
        solicitudAumentoActivity.lbl_data_fecha = null;
        solicitudAumentoActivity.texto_leyenda_final = null;
        solicitudAumentoActivity.boton_enviar = null;
        solicitudAumentoActivity.lnlTitularDividerSolicitud = null;
        solicitudAumentoActivity.lnlTitularSolicitud = null;
        solicitudAumentoActivity.lnlTipoCuentaSolicitud = null;
        solicitudAumentoActivity.lnlTipoSolicitud = null;
        solicitudAumentoActivity.lnlNumeroSolicitud = null;
        solicitudAumentoActivity.txtTitularSolicitud = null;
        solicitudAumentoActivity.txtAliasSolicitud = null;
        solicitudAumentoActivity.lnlAliasSolicitud = null;
        solicitudAumentoActivity.txtTipoCuentaSolicitud = null;
        solicitudAumentoActivity.lnlCuitSolicitud = null;
        solicitudAumentoActivity.lnlBancoDestinoSolicitud = null;
        solicitudAumentoActivity.lnlCBUSolicitud = null;
        solicitudAumentoActivity.txtTipoSolicitud = null;
        solicitudAumentoActivity.txtNumeroSolicitud = null;
        solicitudAumentoActivity.txtCBUSolicitud = null;
        solicitudAumentoActivity.txtBancoDestinoSolicitud = null;
        solicitudAumentoActivity.txtCuitSolicitud = null;
        solicitudAumentoActivity.data_importe = null;
        solicitudAumentoActivity.data_para = null;
        solicitudAumentoActivity.data_Titular = null;
        solicitudAumentoActivity.data_tipo_cuenta = null;
        solicitudAumentoActivity.data_row_tipo_cuenta = null;
        solicitudAumentoActivity.data_banco_destino = null;
        solicitudAumentoActivity.data_row_banco_destino = null;
        solicitudAumentoActivity.data_tipo = null;
        solicitudAumentoActivity.data_numero = null;
        solicitudAumentoActivity.data_de = null;
        solicitudAumentoActivity.data_fecha = null;
        solicitudAumentoActivity.data_leyenda = null;
        solicitudAumentoActivity.btn_confirmar = null;
        solicitudAumentoActivity.comprobante_data_importe = null;
        solicitudAumentoActivity.comprobante_data_para = null;
        solicitudAumentoActivity.comprobante_data_Titular = null;
        solicitudAumentoActivity.comprobante_data_tipo_cuenta = null;
        solicitudAumentoActivity.comprobante_data_row_tipo_cuenta = null;
        solicitudAumentoActivity.comprobante_data_row_banco_destino = null;
        solicitudAumentoActivity.comprobante_data_banco_destino = null;
        solicitudAumentoActivity.comprobante_data_tipo = null;
        solicitudAumentoActivity.comprobante_data_numero = null;
        solicitudAumentoActivity.comprobante_data_de = null;
        solicitudAumentoActivity.comprobante_data_fecha = null;
        solicitudAumentoActivity.comprobante_data_nroComprobante = null;
        solicitudAumentoActivity.btn_volver = null;
        solicitudAumentoActivity.comprobanteSolicitud = null;
        solicitudAumentoActivity.data_leyenda_comprobante = null;
    }
}
