package ar.com.santander.rio.mbanking.app.ui.activities;

import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.ViewFlipper;
import ar.com.santander.rio.mbanking.R;
import ar.com.santander.rio.mbanking.view.CustomSpinner;
import ar.com.santander.rio.mbanking.view.NumericEditTextWithPrefixAccesibility;
import butterknife.ButterKnife.Finder;

public class SuscribirFondoActivity$$ViewInjector {
    public static void inject(Finder finder, SuscribirFondoActivity suscribirFondoActivity, Object obj) {
        suscribirFondoActivity.mControlPager = (ViewFlipper) finder.findRequiredView(obj, R.id.activity_suscribir_fondo_viewFlipper, "field 'mControlPager'");
        suscribirFondoActivity.rowSelectorCuentasSuscribir = (LinearLayout) finder.findRequiredView(obj, R.id.F24_20_lnl_selectorCuentas, "field 'rowSelectorCuentasSuscribir'");
        suscribirFondoActivity.lblTitlefondo = (TextView) finder.findRequiredView(obj, R.id.F24_20_LBL_TITLE, "field 'lblTitlefondo'");
        suscribirFondoActivity.rllSelectedAmountType = (RelativeLayout) finder.findRequiredView(obj, R.id.F24_20_RLL_SELECTED_AMOUNT_TYPE, "field 'rllSelectedAmountType'");
        suscribirFondoActivity.vgSelectorAccount = (CustomSpinner) finder.findRequiredView(obj, R.id.F24_20_vgSelectorAccount, "field 'vgSelectorAccount'");
        suscribirFondoActivity.lblDataCuentaTitulo = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_data_cuentaTitulo, "field 'lblDataCuentaTitulo'");
        suscribirFondoActivity.lblSelectedAmountType = (TextView) finder.findRequiredView(obj, R.id.F24_20_LBL_SELECTED_AMOUNT_TYPE, "field 'lblSelectedAmountType'");
        suscribirFondoActivity.inpAmount = (NumericEditTextWithPrefixAccesibility) finder.findRequiredView(obj, R.id.F24_20_INP_AMOUNT, "field 'inpAmount'");
        suscribirFondoActivity.lblDataFondo = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_data_fondo, "field 'lblDataFondo'");
        suscribirFondoActivity.lblDataValorCuotapartes = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_data_valorCuotaparte, "field 'lblDataValorCuotapartes'");
        suscribirFondoActivity.rowPlazoPago = (LinearLayout) finder.findRequiredView(obj, R.id.F24_20_row_plazoPago, "field 'rowPlazoPago'");
        suscribirFondoActivity.btnContinuar = (Button) finder.findRequiredView(obj, R.id.F24_20_btn_continuar, "field 'btnContinuar'");
        suscribirFondoActivity.rowImporteTotal = (LinearLayout) finder.findRequiredView(obj, R.id.F24_20_row_importeTotal, "field 'rowImporteTotal'");
        suscribirFondoActivity.rowCuotaPartes = (LinearLayout) finder.findRequiredView(obj, R.id.F24_20_row_cuotaPartes, "field 'rowCuotaPartes'");
        suscribirFondoActivity.lblDataOrigen = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_data_origen, "field 'lblDataOrigen'");
        suscribirFondoActivity.imgImportre = (ImageView) finder.findRequiredView(obj, R.id.F24_20_IMG_SELECTED_CURRENCY_CHEVRON, "field 'imgImportre'");
        suscribirFondoActivity.rowCuentaTituloBottom = (LinearLayout) finder.findRequiredView(obj, R.id.F24_20_row_cuentaTitulo_bottom, "field 'rowCuentaTituloBottom'");
        suscribirFondoActivity.lblDataCuentaTituloBottom = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_data_cuentaTitulo_bottom, "field 'lblDataCuentaTituloBottom'");
        suscribirFondoActivity.rowValorCuotaparte = (LinearLayout) finder.findRequiredView(obj, R.id.F24_20_row_valorCuotaparte, "field 'rowValorCuotaparte'");
        suscribirFondoActivity.imgCheckBoxValidar = (ImageView) finder.findRequiredView(obj, R.id.F24_20_img_checkbox_tyc, "field 'imgCheckBoxValidar'");
        suscribirFondoActivity.leyendaLegal = (TextView) finder.findRequiredView(obj, R.id.F24_20_lbl_leyendaLegal, "field 'leyendaLegal'");
        suscribirFondoActivity.lblTitleConfirmarSuscripcion = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_title, "field 'lblTitleConfirmarSuscripcion'");
        suscribirFondoActivity.lblDataFondoSuscribirConfirmar = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_fondoRescatar, "field 'lblDataFondoSuscribirConfirmar'");
        suscribirFondoActivity.lblDataImporteConfirmar = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_importe, "field 'lblDataImporteConfirmar'");
        suscribirFondoActivity.lblTxtCuotaparte = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_cuotaParte, "field 'lblTxtCuotaparte'");
        suscribirFondoActivity.lblDataCuotaparteConfirmar = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_cuotaparte, "field 'lblDataCuotaparteConfirmar'");
        suscribirFondoActivity.lblDataValorCuotaparteConfirmar = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_valorCuotaParte, "field 'lblDataValorCuotaparteConfirmar'");
        suscribirFondoActivity.lblDataOrigenConfirmar = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_origen, "field 'lblDataOrigenConfirmar'");
        suscribirFondoActivity.lblDataCuentaTituloConfirmar = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_cuentaTitulo, "field 'lblDataCuentaTituloConfirmar'");
        suscribirFondoActivity.lblDataFondoConfirmar = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_data_fondo, "field 'lblDataFondoConfirmar'");
        suscribirFondoActivity.btnConfirmarSuscripcion = (Button) finder.findRequiredView(obj, R.id.F24_21_btn_confirmar, "field 'btnConfirmarSuscripcion'");
        suscribirFondoActivity.rowCuentaDestinoConfirmar = (LinearLayout) finder.findRequiredView(obj, R.id.F24_21_row_cuentaDestino, "field 'rowCuentaDestinoConfirmar'");
        suscribirFondoActivity.lblConectorVerTyC = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_conectorVerTerminos, "field 'lblConectorVerTyC'");
        suscribirFondoActivity.imgCheckboxReglamento = (ImageView) finder.findRequiredView(obj, R.id.F24_21_img_checkbox_tyc, "field 'imgCheckboxReglamento'");
        suscribirFondoActivity.lblVerTyC = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_verTerminos, "field 'lblVerTyC'");
        suscribirFondoActivity.lblConfirmarTerminosLegales = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_terminosLegales, "field 'lblConfirmarTerminosLegales'");
        suscribirFondoActivity.rlTerminosYCondiciones = (RelativeLayout) finder.findRequiredView(obj, R.id.F24_21_rll_terminosCondiciones, "field 'rlTerminosYCondiciones'");
        suscribirFondoActivity.rowPlazoDePago = (LinearLayout) finder.findRequiredView(obj, R.id.F24_21_row_plazoPago, "field 'rowPlazoDePago'");
        suscribirFondoActivity.txtValorCuotaparte = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_valorCuotaParte, "field 'txtValorCuotaparte'");
        suscribirFondoActivity.rowValorCuotaparteConfirmar = (LinearLayout) finder.findRequiredView(obj, R.id.F24_21_row_valorCuotaparteConfirmar, "field 'rowValorCuotaparteConfirmar'");
        suscribirFondoActivity.separatorTexto = finder.findRequiredView(obj, R.id.F24_21_separationSection, "field 'separatorTexto'");
        suscribirFondoActivity.lblVerReglamento = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_ver_reglamento, "field 'lblVerReglamento'");
        suscribirFondoActivity.lblDataInfoRiesgo = (TextView) finder.findRequiredView(obj, R.id.F24_XX_LBL_DATA_INFO_RIESGO, "field 'lblDataInfoRiesgo'");
        suscribirFondoActivity.btnAceptarRiesgo = (TextView) finder.findRequiredView(obj, R.id.F24_XX_BTN_ACEPTAR_RIESGO, "field 'btnAceptarRiesgo'");
        suscribirFondoActivity.btnNoAceptaRiesgo = (TextView) finder.findRequiredView(obj, R.id.F24_XX_BTN_NO_ACEPTA_RIESGO, "field 'btnNoAceptaRiesgo'");
        suscribirFondoActivity.lblFueraHorarioMensaje = (TextView) finder.findRequiredView(obj, R.id.FXX_XX_LBL_MESSAGE, "field 'lblFueraHorarioMensaje'");
        suscribirFondoActivity.txtTitleComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_title, "field 'txtTitleComprobante'");
        suscribirFondoActivity.txtTitleFondoSuscribir = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_fondoRescatar, "field 'txtTitleFondoSuscribir'");
        suscribirFondoActivity.lblDataImporteComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_importeHeader, "field 'lblDataImporteComprobante'");
        suscribirFondoActivity.lblTxtCuotapartesComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_cuotaparteHeader, "field 'lblTxtCuotapartesComprobante'");
        suscribirFondoActivity.lblDataCuotapartesComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_cuotaparteHeader, "field 'lblDataCuotapartesComprobante'");
        suscribirFondoActivity.lblDataValorCuotaparteComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_valorCuotaparteHeader, "field 'lblDataValorCuotaparteComprobante'");
        suscribirFondoActivity.lblDataFechaHoraComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_fechaHora, "field 'lblDataFechaHoraComprobante'");
        suscribirFondoActivity.lblDataOrigenComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_cuenta_debito, "field 'lblDataOrigenComprobante'");
        suscribirFondoActivity.lblDataCuentaTituloComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_cuentaTitulo, "field 'lblDataCuentaTituloComprobante'");
        suscribirFondoActivity.lblDatafondoComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_fondo, "field 'lblDatafondoComprobante'");
        suscribirFondoActivity.rowCuentaDestinoComprobante = (LinearLayout) finder.findRequiredView(obj, R.id.F24_22_row_cuentaDestino, "field 'rowCuentaDestinoComprobante'");
        suscribirFondoActivity.lblDataImporteBottomComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_importeBottom, "field 'lblDataImporteBottomComprobante'");
        suscribirFondoActivity.lblDataValorCuotaparteBottomComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_valorCuotaparteBottom, "field 'lblDataValorCuotaparteBottomComprobante'");
        suscribirFondoActivity.lblDataCuotaparteBottomComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_cuotapartesBottom, "field 'lblDataCuotaparteBottomComprobante'");
        suscribirFondoActivity.lblDataCertificadoComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_data_certificado, "field 'lblDataCertificadoComprobante'");
        suscribirFondoActivity.btnVolverComprobante = (Button) finder.findRequiredView(obj, R.id.F24_22_btn_volver, "field 'btnVolverComprobante'");
        suscribirFondoActivity.comprobanteOperacion = (ScrollView) finder.findRequiredView(obj, R.id.F24_22_scrollViewComprobante, "field 'comprobanteOperacion'");
        suscribirFondoActivity.lblComprobanteTerminosLegales = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_terminosLegales, "field 'lblComprobanteTerminosLegales'");
        suscribirFondoActivity.rowPlazoPagoComprobante = (LinearLayout) finder.findRequiredView(obj, R.id.F24_22_row_plazo_de_pago, "field 'rowPlazoPagoComprobante'");
        suscribirFondoActivity.separatorSectionComprobante = finder.findRequiredView(obj, R.id.F24_22_separatorSection_comprobante, "field 'separatorSectionComprobante'");
        suscribirFondoActivity.lblTextValorcuotaparte = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_valorCuotaparteHeader, "field 'lblTextValorcuotaparte'");
        suscribirFondoActivity.lbltextValorCuotapartes = (LinearLayout) finder.findRequiredView(obj, R.id.F24_22_row_valorCuotaparteBottom, "field 'lbltextValorCuotapartes'");
        suscribirFondoActivity.lbltextCuotapartes = (LinearLayout) finder.findRequiredView(obj, R.id.F24_22_row_cuotapartesBottom, "field 'lbltextCuotapartes'");
        suscribirFondoActivity.lblCertificadoComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_22_lbl_certificado, "field 'lblCertificadoComprobante'");
    }

    public static void reset(SuscribirFondoActivity suscribirFondoActivity) {
        suscribirFondoActivity.mControlPager = null;
        suscribirFondoActivity.rowSelectorCuentasSuscribir = null;
        suscribirFondoActivity.lblTitlefondo = null;
        suscribirFondoActivity.rllSelectedAmountType = null;
        suscribirFondoActivity.vgSelectorAccount = null;
        suscribirFondoActivity.lblDataCuentaTitulo = null;
        suscribirFondoActivity.lblSelectedAmountType = null;
        suscribirFondoActivity.inpAmount = null;
        suscribirFondoActivity.lblDataFondo = null;
        suscribirFondoActivity.lblDataValorCuotapartes = null;
        suscribirFondoActivity.rowPlazoPago = null;
        suscribirFondoActivity.btnContinuar = null;
        suscribirFondoActivity.rowImporteTotal = null;
        suscribirFondoActivity.rowCuotaPartes = null;
        suscribirFondoActivity.lblDataOrigen = null;
        suscribirFondoActivity.imgImportre = null;
        suscribirFondoActivity.rowCuentaTituloBottom = null;
        suscribirFondoActivity.lblDataCuentaTituloBottom = null;
        suscribirFondoActivity.rowValorCuotaparte = null;
        suscribirFondoActivity.imgCheckBoxValidar = null;
        suscribirFondoActivity.leyendaLegal = null;
        suscribirFondoActivity.lblTitleConfirmarSuscripcion = null;
        suscribirFondoActivity.lblDataFondoSuscribirConfirmar = null;
        suscribirFondoActivity.lblDataImporteConfirmar = null;
        suscribirFondoActivity.lblTxtCuotaparte = null;
        suscribirFondoActivity.lblDataCuotaparteConfirmar = null;
        suscribirFondoActivity.lblDataValorCuotaparteConfirmar = null;
        suscribirFondoActivity.lblDataOrigenConfirmar = null;
        suscribirFondoActivity.lblDataCuentaTituloConfirmar = null;
        suscribirFondoActivity.lblDataFondoConfirmar = null;
        suscribirFondoActivity.btnConfirmarSuscripcion = null;
        suscribirFondoActivity.rowCuentaDestinoConfirmar = null;
        suscribirFondoActivity.lblConectorVerTyC = null;
        suscribirFondoActivity.imgCheckboxReglamento = null;
        suscribirFondoActivity.lblVerTyC = null;
        suscribirFondoActivity.lblConfirmarTerminosLegales = null;
        suscribirFondoActivity.rlTerminosYCondiciones = null;
        suscribirFondoActivity.rowPlazoDePago = null;
        suscribirFondoActivity.txtValorCuotaparte = null;
        suscribirFondoActivity.rowValorCuotaparteConfirmar = null;
        suscribirFondoActivity.separatorTexto = null;
        suscribirFondoActivity.lblVerReglamento = null;
        suscribirFondoActivity.lblDataInfoRiesgo = null;
        suscribirFondoActivity.btnAceptarRiesgo = null;
        suscribirFondoActivity.btnNoAceptaRiesgo = null;
        suscribirFondoActivity.lblFueraHorarioMensaje = null;
        suscribirFondoActivity.txtTitleComprobante = null;
        suscribirFondoActivity.txtTitleFondoSuscribir = null;
        suscribirFondoActivity.lblDataImporteComprobante = null;
        suscribirFondoActivity.lblTxtCuotapartesComprobante = null;
        suscribirFondoActivity.lblDataCuotapartesComprobante = null;
        suscribirFondoActivity.lblDataValorCuotaparteComprobante = null;
        suscribirFondoActivity.lblDataFechaHoraComprobante = null;
        suscribirFondoActivity.lblDataOrigenComprobante = null;
        suscribirFondoActivity.lblDataCuentaTituloComprobante = null;
        suscribirFondoActivity.lblDatafondoComprobante = null;
        suscribirFondoActivity.rowCuentaDestinoComprobante = null;
        suscribirFondoActivity.lblDataImporteBottomComprobante = null;
        suscribirFondoActivity.lblDataValorCuotaparteBottomComprobante = null;
        suscribirFondoActivity.lblDataCuotaparteBottomComprobante = null;
        suscribirFondoActivity.lblDataCertificadoComprobante = null;
        suscribirFondoActivity.btnVolverComprobante = null;
        suscribirFondoActivity.comprobanteOperacion = null;
        suscribirFondoActivity.lblComprobanteTerminosLegales = null;
        suscribirFondoActivity.rowPlazoPagoComprobante = null;
        suscribirFondoActivity.separatorSectionComprobante = null;
        suscribirFondoActivity.lblTextValorcuotaparte = null;
        suscribirFondoActivity.lbltextValorCuotapartes = null;
        suscribirFondoActivity.lbltextCuotapartes = null;
        suscribirFondoActivity.lblCertificadoComprobante = null;
    }
}
