package ar.com.santander.rio.mbanking.app.ui.activities;

import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.ViewFlipper;
import ar.com.santander.rio.mbanking.R;
import ar.com.santander.rio.mbanking.view.CustomSpinner;
import ar.com.santander.rio.mbanking.view.NumericEditTextWithPrefixAccesibility;
import butterknife.ButterKnife.Finder;

public class TransferirFondoActivity$$ViewInjector {
    public static void inject(Finder finder, TransferirFondoActivity transferirFondoActivity, Object obj) {
        transferirFondoActivity.mControlPager = (ViewFlipper) finder.findRequiredView(obj, R.id.fondos_transferir_view_flipper, "field 'mControlPager'");
        transferirFondoActivity.rllSelectedAmountType = (RelativeLayout) finder.findRequiredView(obj, R.id.F24_30_RLL_SELECTED_AMOUNT_TYPE, "field 'rllSelectedAmountType'");
        transferirFondoActivity.vgSelectorAccount = (CustomSpinner) finder.findRequiredView(obj, R.id.F24_30_vgSelectorAccount, "field 'vgSelectorAccount'");
        transferirFondoActivity.lblDataCuentaTitulo = (TextView) finder.findRequiredView(obj, R.id.F24_30_lbl_data_cuentaTitulo, "field 'lblDataCuentaTitulo'");
        transferirFondoActivity.lblSelectedAmountType = (TextView) finder.findRequiredView(obj, R.id.F24_30_LBL_SELECTED_AMOUNT_TYPE, "field 'lblSelectedAmountType'");
        transferirFondoActivity.inpAmount = (NumericEditTextWithPrefixAccesibility) finder.findRequiredView(obj, R.id.F24_30_INP_AMOUNT, "field 'inpAmount'");
        transferirFondoActivity.lblDataFondo = (TextView) finder.findRequiredView(obj, R.id.F24_30_lbl_data_fondoOrigen, "field 'lblDataFondo'");
        transferirFondoActivity.lblDataImporteTotal = (TextView) finder.findRequiredView(obj, R.id.F24_30_lbl_data_importeTotal, "field 'lblDataImporteTotal'");
        transferirFondoActivity.lblDataCuotapartes = (TextView) finder.findRequiredView(obj, R.id.F24_30_lbl_data_cuotaPartes, "field 'lblDataCuotapartes'");
        transferirFondoActivity.lblDataValorCuotapartes = (TextView) finder.findRequiredView(obj, R.id.F24_30_lbl_data_valorCuotaparte, "field 'lblDataValorCuotapartes'");
        transferirFondoActivity.lblDataFondoDestino = (TextView) finder.findRequiredView(obj, R.id.F24_30_lbl_data_fondoDestino, "field 'lblDataFondoDestino'");
        transferirFondoActivity.btnContinuar = (Button) finder.findRequiredView(obj, R.id.F24_30_btn_continuar, "field 'btnContinuar'");
        transferirFondoActivity.lnlSelectorCuentas = (LinearLayout) finder.findRequiredView(obj, R.id.F24_30_lnl_selectorCuentas, "field 'lnlSelectorCuentas'");
        transferirFondoActivity.lnlCuotapartes = (LinearLayout) finder.findRequiredView(obj, R.id.F24_30_row_cuotaPartes, "field 'lnlCuotapartes'");
        transferirFondoActivity.lnlValorCuotaparte = (LinearLayout) finder.findRequiredView(obj, R.id.F24_30_row_valorCuotaparte, "field 'lnlValorCuotaparte'");
        transferirFondoActivity.lnlAceptacionEjecucion = (LinearLayout) finder.findRequiredView(obj, R.id.F24_30_aceptacion_ejecucion, "field 'lnlAceptacionEjecucion'");
        transferirFondoActivity.lblAceptacionEjecucion = (TextView) finder.findRequiredView(obj, R.id.F24_30_lbl_aceptacion_ejecucion, "field 'lblAceptacionEjecucion'");
        transferirFondoActivity.imgCheckBoxValidar = (ImageView) finder.findRequiredView(obj, R.id.F24_30_img_checkbox, "field 'imgCheckBoxValidar'");
        transferirFondoActivity.leyendaLegal = (TextView) finder.findRequiredView(obj, R.id.F24_30_lbl_leyendaLegal, "field 'leyendaLegal'");
        transferirFondoActivity.lblDataConfirmarFondoOrigenHeader = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_data_fondoOrigenHeader, "field 'lblDataConfirmarFondoOrigenHeader'");
        transferirFondoActivity.lblDataConfirmarImporte = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_data_importe, "field 'lblDataConfirmarImporte'");
        transferirFondoActivity.lblDataConfirmarFondoDestinoHeader = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_data_fondoDestinoHeader, "field 'lblDataConfirmarFondoDestinoHeader'");
        transferirFondoActivity.lblDataConfirmarCuentaTitulo = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_data_cuentaTitulo, "field 'lblDataConfirmarCuentaTitulo'");
        transferirFondoActivity.lblDataConfirmarFondoOrigen = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_data_fondoOrigenDetail, "field 'lblDataConfirmarFondoOrigen'");
        transferirFondoActivity.lblDataConfirmarFondoOrigenCuotapartes = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_data_cuotapartesOrigen, "field 'lblDataConfirmarFondoOrigenCuotapartes'");
        transferirFondoActivity.lblDataConfirmarValorCuotapartesOrigen = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_data_valorCuotapartesOrigen, "field 'lblDataConfirmarValorCuotapartesOrigen'");
        transferirFondoActivity.lblDataConfirmarFondoDestino = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_data_fondoDestinoDetail, "field 'lblDataConfirmarFondoDestino'");
        transferirFondoActivity.lblDataConfirmarFondoDestinoCuotapartes = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_data_cuotapartesDestino, "field 'lblDataConfirmarFondoDestinoCuotapartes'");
        transferirFondoActivity.lblDataConfirmarValorCuotapartesDestino = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_data_valorCuotapartesDestino, "field 'lblDataConfirmarValorCuotapartesDestino'");
        transferirFondoActivity.lblDataConfirmarImporteDetail = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_data_importeDetail, "field 'lblDataConfirmarImporteDetail'");
        transferirFondoActivity.imgCheckboxReglamento = (ImageView) finder.findRequiredView(obj, R.id.F24_31_img_checkbox_tyc, "field 'imgCheckboxReglamento'");
        transferirFondoActivity.lblVerReglamento = (TextView) finder.findRequiredView(obj, R.id.F24_21_lbl_ver_reglamento, "field 'lblVerReglamento'");
        transferirFondoActivity.lblConectorVerTyC = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_conectorVerTerminos, "field 'lblConectorVerTyC'");
        transferirFondoActivity.lblVerTyC = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_verTerminos, "field 'lblVerTyC'");
        transferirFondoActivity.lblConfirmarTerminosLegales = (TextView) finder.findRequiredView(obj, R.id.F24_31_lbl_terminosLegales, "field 'lblConfirmarTerminosLegales'");
        transferirFondoActivity.btnConfirmar = (Button) finder.findRequiredView(obj, R.id.F24_31_btn_confirmar, "field 'btnConfirmar'");
        transferirFondoActivity.rowValorCuotapartesComprobante = (LinearLayout) finder.findRequiredView(obj, R.id.F24_31_row_valorCuotapartesOrigen, "field 'rowValorCuotapartesComprobante'");
        transferirFondoActivity.rowCuotapartesComprobante = (LinearLayout) finder.findRequiredView(obj, R.id.F24_31_row_cuotapartesDestino, "field 'rowCuotapartesComprobante'");
        transferirFondoActivity.rowValorCuotapartesDestinoComprobante = (LinearLayout) finder.findRequiredView(obj, R.id.F24_31_row_valorCuotapartesDestino, "field 'rowValorCuotapartesDestinoComprobante'");
        transferirFondoActivity.rowCuotapartes = (LinearLayout) finder.findRequiredView(obj, R.id.F24_31_row_cuotapartesOrigen, "field 'rowCuotapartes'");
        transferirFondoActivity.lblDataInfoRiesgo = (TextView) finder.findRequiredView(obj, R.id.F24_XX_LBL_DATA_INFO_RIESGO, "field 'lblDataInfoRiesgo'");
        transferirFondoActivity.btnAceptarRiesgo = (TextView) finder.findRequiredView(obj, R.id.F24_XX_BTN_ACEPTAR_RIESGO, "field 'btnAceptarRiesgo'");
        transferirFondoActivity.btnNoAceptaRiesgo = (TextView) finder.findRequiredView(obj, R.id.F24_XX_BTN_NO_ACEPTA_RIESGO, "field 'btnNoAceptaRiesgo'");
        transferirFondoActivity.lblFueraHorarioMensaje = (TextView) finder.findRequiredView(obj, R.id.FXX_XX_LBL_MESSAGE, "field 'lblFueraHorarioMensaje'");
        transferirFondoActivity.comprobanteOperacion = (ScrollView) finder.findRequiredView(obj, R.id.F24_32_scrollViewComprobante, "field 'comprobanteOperacion'");
        transferirFondoActivity.lblDataComprobanteFondoOrigenHeader = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_fondoOrigenHeader, "field 'lblDataComprobanteFondoOrigenHeader'");
        transferirFondoActivity.lblDataComprobanteImporte = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_importe, "field 'lblDataComprobanteImporte'");
        transferirFondoActivity.lblDataComprobanteFondoDestinoHeader = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_fondoDestinoHeader, "field 'lblDataComprobanteFondoDestinoHeader'");
        transferirFondoActivity.lblDataComprobanteFechaHora = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_fechaHora, "field 'lblDataComprobanteFechaHora'");
        transferirFondoActivity.lblDataComprobanteCuentaTitulo = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_cuentaTitulo, "field 'lblDataComprobanteCuentaTitulo'");
        transferirFondoActivity.lblDataComprobanteImporteEstimadoBottom = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_importeEstimado, "field 'lblDataComprobanteImporteEstimadoBottom'");
        transferirFondoActivity.lblDataComprobanteFondoOrigenBottom = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_fondoOrigenBottom, "field 'lblDataComprobanteFondoOrigenBottom'");
        transferirFondoActivity.lblDataComprobanteFondoOrigenCuotapartesBottom = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_cuotapartesOrigenBottom, "field 'lblDataComprobanteFondoOrigenCuotapartesBottom'");
        transferirFondoActivity.lblDataValorCuotapartesOrigenBottom = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_valorCuotaparteOrigenBottom, "field 'lblDataValorCuotapartesOrigenBottom'");
        transferirFondoActivity.lblDataComprobanteFondoDestinoBottom = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_fondoDestinoBottom, "field 'lblDataComprobanteFondoDestinoBottom'");
        transferirFondoActivity.lblDataComprobanteFondoDestinoCuotapartesBottom = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_cuotapartesDestinoBottom, "field 'lblDataComprobanteFondoDestinoCuotapartesBottom'");
        transferirFondoActivity.lblDataComprobanteValorCuotapartesDestinoBottom = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_valorCuotaparteDestinoBottom, "field 'lblDataComprobanteValorCuotapartesDestinoBottom'");
        transferirFondoActivity.lblComprobanteTerminosLegales = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_terminosLegales, "field 'lblComprobanteTerminosLegales'");
        transferirFondoActivity.lblDataComprobanteCertificado = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_data_certificado, "field 'lblDataComprobanteCertificado'");
        transferirFondoActivity.btnVolver = (Button) finder.findRequiredView(obj, R.id.F24_32_btn_volver, "field 'btnVolver'");
        transferirFondoActivity.rowValorCuotapartesComp = (LinearLayout) finder.findRequiredView(obj, R.id.F24_32_row_valorCuotaparteOrigenBottom, "field 'rowValorCuotapartesComp'");
        transferirFondoActivity.rowCuotapartesdestinoComp = (LinearLayout) finder.findRequiredView(obj, R.id.F24_32_row_cuotapartesDestinoBottom, "field 'rowCuotapartesdestinoComp'");
        transferirFondoActivity.rowValorCuotaparteDestinoComp = (LinearLayout) finder.findRequiredView(obj, R.id.F24_32_row_valorCuotaparteDestinoBottom, "field 'rowValorCuotaparteDestinoComp'");
        transferirFondoActivity.rowCuotapartesComp = (LinearLayout) finder.findRequiredView(obj, R.id.F24_32_row_cuotapartesOrigenBottom, "field 'rowCuotapartesComp'");
        transferirFondoActivity.lblCertificadoComprobante = (TextView) finder.findRequiredView(obj, R.id.F24_32_lbl_certificado, "field 'lblCertificadoComprobante'");
    }

    public static void reset(TransferirFondoActivity transferirFondoActivity) {
        transferirFondoActivity.mControlPager = null;
        transferirFondoActivity.rllSelectedAmountType = null;
        transferirFondoActivity.vgSelectorAccount = null;
        transferirFondoActivity.lblDataCuentaTitulo = null;
        transferirFondoActivity.lblSelectedAmountType = null;
        transferirFondoActivity.inpAmount = null;
        transferirFondoActivity.lblDataFondo = null;
        transferirFondoActivity.lblDataImporteTotal = null;
        transferirFondoActivity.lblDataCuotapartes = null;
        transferirFondoActivity.lblDataValorCuotapartes = null;
        transferirFondoActivity.lblDataFondoDestino = null;
        transferirFondoActivity.btnContinuar = null;
        transferirFondoActivity.lnlSelectorCuentas = null;
        transferirFondoActivity.lnlCuotapartes = null;
        transferirFondoActivity.lnlValorCuotaparte = null;
        transferirFondoActivity.lnlAceptacionEjecucion = null;
        transferirFondoActivity.lblAceptacionEjecucion = null;
        transferirFondoActivity.imgCheckBoxValidar = null;
        transferirFondoActivity.leyendaLegal = null;
        transferirFondoActivity.lblDataConfirmarFondoOrigenHeader = null;
        transferirFondoActivity.lblDataConfirmarImporte = null;
        transferirFondoActivity.lblDataConfirmarFondoDestinoHeader = null;
        transferirFondoActivity.lblDataConfirmarCuentaTitulo = null;
        transferirFondoActivity.lblDataConfirmarFondoOrigen = null;
        transferirFondoActivity.lblDataConfirmarFondoOrigenCuotapartes = null;
        transferirFondoActivity.lblDataConfirmarValorCuotapartesOrigen = null;
        transferirFondoActivity.lblDataConfirmarFondoDestino = null;
        transferirFondoActivity.lblDataConfirmarFondoDestinoCuotapartes = null;
        transferirFondoActivity.lblDataConfirmarValorCuotapartesDestino = null;
        transferirFondoActivity.lblDataConfirmarImporteDetail = null;
        transferirFondoActivity.imgCheckboxReglamento = null;
        transferirFondoActivity.lblVerReglamento = null;
        transferirFondoActivity.lblConectorVerTyC = null;
        transferirFondoActivity.lblVerTyC = null;
        transferirFondoActivity.lblConfirmarTerminosLegales = null;
        transferirFondoActivity.btnConfirmar = null;
        transferirFondoActivity.rowValorCuotapartesComprobante = null;
        transferirFondoActivity.rowCuotapartesComprobante = null;
        transferirFondoActivity.rowValorCuotapartesDestinoComprobante = null;
        transferirFondoActivity.rowCuotapartes = null;
        transferirFondoActivity.lblDataInfoRiesgo = null;
        transferirFondoActivity.btnAceptarRiesgo = null;
        transferirFondoActivity.btnNoAceptaRiesgo = null;
        transferirFondoActivity.lblFueraHorarioMensaje = null;
        transferirFondoActivity.comprobanteOperacion = null;
        transferirFondoActivity.lblDataComprobanteFondoOrigenHeader = null;
        transferirFondoActivity.lblDataComprobanteImporte = null;
        transferirFondoActivity.lblDataComprobanteFondoDestinoHeader = null;
        transferirFondoActivity.lblDataComprobanteFechaHora = null;
        transferirFondoActivity.lblDataComprobanteCuentaTitulo = null;
        transferirFondoActivity.lblDataComprobanteImporteEstimadoBottom = null;
        transferirFondoActivity.lblDataComprobanteFondoOrigenBottom = null;
        transferirFondoActivity.lblDataComprobanteFondoOrigenCuotapartesBottom = null;
        transferirFondoActivity.lblDataValorCuotapartesOrigenBottom = null;
        transferirFondoActivity.lblDataComprobanteFondoDestinoBottom = null;
        transferirFondoActivity.lblDataComprobanteFondoDestinoCuotapartesBottom = null;
        transferirFondoActivity.lblDataComprobanteValorCuotapartesDestinoBottom = null;
        transferirFondoActivity.lblComprobanteTerminosLegales = null;
        transferirFondoActivity.lblDataComprobanteCertificado = null;
        transferirFondoActivity.btnVolver = null;
        transferirFondoActivity.rowValorCuotapartesComp = null;
        transferirFondoActivity.rowCuotapartesdestinoComp = null;
        transferirFondoActivity.rowValorCuotaparteDestinoComp = null;
        transferirFondoActivity.rowCuotapartesComp = null;
        transferirFondoActivity.lblCertificadoComprobante = null;
    }
}
