package ar.com.santander.rio.mbanking.app.ui.fragments.publico;

import android.support.constraint.ConstraintLayout;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import ar.com.santander.rio.mbanking.R;
import ar.com.santander.rio.mbanking.view.EditTextValidator;
import butterknife.ButterKnife.Finder;

public class LoginFragment$$ViewInjector {
    public static void inject(Finder finder, LoginFragment loginFragment, Object obj) {
        loginFragment.mControlPager = (ViewFlipper) finder.findRequiredView(obj, R.id.vgLogin, "field 'mControlPager'");
        loginFragment.topView = (ConstraintLayout) finder.findRequiredView(obj, R.id.f121hometoptradicional, "field 'topView'");
        loginFragment.topViewNoTradicional = (ConstraintLayout) finder.findRequiredView(obj, R.id.f120hometopnotradicional, "field 'topViewNoTradicional'");
        loginFragment.loginIngresar = (Button) finder.findRequiredView(obj, R.id.loginIngresar, "field 'loginIngresar'");
        loginFragment.loginIngresarNoTradicional = (Button) finder.findRequiredView(obj, R.id.loginIngresarNoTracional, "field 'loginIngresarNoTradicional'");
        loginFragment.loginTextAction = (TextView) finder.findRequiredView(obj, R.id.loginTextAction, "field 'loginTextAction'");
        loginFragment.loginPrimerIngresoTextAction = finder.findRequiredView(obj, R.id.lnl_loginPrimerIngresoTextAction, "field 'loginPrimerIngresoTextAction'");
        loginFragment.loginTextActionNoTradicional = (TextView) finder.findRequiredView(obj, R.id.loginTextActionNoTradicional, "field 'loginTextActionNoTradicional'");
        loginFragment.loginTradicional = finder.findRequiredView(obj, R.id.f127loginformtradicional, "field 'loginTradicional'");
        loginFragment.loginSinonimo = finder.findRequiredView(obj, R.id.f128loginformusuarioSinonimo, "field 'loginSinonimo'");
        loginFragment.loginSinonimoCallToAction = finder.findRequiredView(obj, R.id.f129loginformusuarioSinonimocalltoaction, "field 'loginSinonimoCallToAction'");
        loginFragment.loginClaveVencida = finder.findRequiredView(obj, R.id.f125loginformclaveVencida, "field 'loginClaveVencida'");
        loginFragment.loginPrimerIngreso = finder.findRequiredView(obj, R.id.f126loginformprimerIngreso, "field 'loginPrimerIngreso'");
        loginFragment.loginAltaUsuario = finder.findRequiredView(obj, R.id.f123loginformaltaUsuario, "field 'loginAltaUsuario'");
        loginFragment.loginCambioUsuario = finder.findRequiredView(obj, R.id.f124loginformcambioUsuario, "field 'loginCambioUsuario'");
        loginFragment.documentoLoginTradicional = (EditTextValidator) finder.findRequiredView(obj, R.id.f163loginformTradicionalnumDocumento, "field 'documentoLoginTradicional'");
        loginFragment.claveLoginTradicional = (EditTextValidator) finder.findRequiredView(obj, R.id.f162loginformTradicionalclave, "field 'claveLoginTradicional'");
        loginFragment.usuarioLoginTradicional = (EditTextValidator) finder.findRequiredView(obj, R.id.f164loginformTradicionalusuario, "field 'usuarioLoginTradicional'");
        loginFragment.viewAyudaTradicional = (ImageView) finder.findRequiredView(obj, R.id.view_ayuda_tradicional, "field 'viewAyudaTradicional'");
        loginFragment.documentoLoginSinonimo = (EditTextValidator) finder.findRequiredView(obj, R.id.f155loginformSinonimonumDocumento, "field 'documentoLoginSinonimo'");
        loginFragment.fechaLoginSinonimo = (EditTextValidator) finder.findRequiredView(obj, R.id.f154loginformSinonimofechaNacimiento, "field 'fechaLoginSinonimo'");
        loginFragment.claveLoginSinonimo = (EditTextValidator) finder.findRequiredView(obj, R.id.f153loginformSinonimoclave, "field 'claveLoginSinonimo'");
        loginFragment.usuarioLoginSinonimo = (EditTextValidator) finder.findRequiredView(obj, R.id.f156loginformSinonimousuario, "field 'usuarioLoginSinonimo'");
        loginFragment.viewAyudaSinonimo = (ImageView) finder.findRequiredView(obj, R.id.view_ayuda_sinonimo, "field 'viewAyudaSinonimo'");
        loginFragment.documentoLoginSinonimoCA = (EditTextValidator) finder.findRequiredView(obj, R.id.f159loginformSinonimoCAnumDocumento, "field 'documentoLoginSinonimoCA'");
        loginFragment.fechaLoginSinonimoCA = (EditTextValidator) finder.findRequiredView(obj, R.id.f158loginformSinonimoCAfechaNacimiento, "field 'fechaLoginSinonimoCA'");
        loginFragment.claveLoginSinonimoCA = (EditTextValidator) finder.findRequiredView(obj, R.id.f157loginformSinonimoCAclave, "field 'claveLoginSinonimoCA'");
        loginFragment.usuarioLoginSinonimoCA = (EditTextValidator) finder.findRequiredView(obj, R.id.f161loginformSinonimoCAusuario, "field 'usuarioLoginSinonimoCA'");
        loginFragment.reusuarioLoginSinonimoCA = (EditTextValidator) finder.findRequiredView(obj, R.id.f160loginformSinonimoCAreusuario, "field 'reusuarioLoginSinonimoCA'");
        loginFragment.viewAyudaSinonimoCA = (ImageView) finder.findRequiredView(obj, R.id.view_ayuda_sinonimoCA, "field 'viewAyudaSinonimoCA'");
        loginFragment.documentoLoginPrimerIngreso = (EditTextValidator) finder.findRequiredView(obj, R.id.f150loginformPrimerIngresonumDocumento, "field 'documentoLoginPrimerIngreso'");
        loginFragment.nuevaClaveLoginPrimerIngreso = (EditTextValidator) finder.findRequiredView(obj, R.id.f149loginformPrimerIngresonuevaClave, "field 'nuevaClaveLoginPrimerIngreso'");
        loginFragment.reingresaClaveLoginPrimerIngreso = (EditTextValidator) finder.findRequiredView(obj, R.id.f151loginformPrimerIngresoreingresaClave, "field 'reingresaClaveLoginPrimerIngreso'");
        loginFragment.generaUsuarioLoginPrimerIngreso = (EditTextValidator) finder.findRequiredView(obj, R.id.f148loginformPrimerIngresogeneraUsuario, "field 'generaUsuarioLoginPrimerIngreso'");
        loginFragment.reingresaUsuarioLoginPrimerIngreso = (EditTextValidator) finder.findRequiredView(obj, R.id.f152loginformPrimerIngresoreingresaUsuario, "field 'reingresaUsuarioLoginPrimerIngreso'");
        loginFragment.claveAntiguaLoginPrimerIngreso = (EditTextValidator) finder.findRequiredView(obj, R.id.f145loginformPrimerIngresoclaveAntigua, "field 'claveAntiguaLoginPrimerIngreso'");
        loginFragment.fechaNacimientoLoginPrimerIngreso = (EditTextValidator) finder.findRequiredView(obj, R.id.f146loginformPrimerIngresofechaNacimiento, "field 'fechaNacimientoLoginPrimerIngreso'");
        loginFragment.fechaNacimientoLoginPrimerIngresoSeparator = finder.findRequiredView(obj, R.id.f147loginformPrimerIngresofechaNacimientoseparator, "field 'fechaNacimientoLoginPrimerIngresoSeparator'");
        loginFragment.viewAyudaPrimerIngreso = (ImageView) finder.findRequiredView(obj, R.id.view_ayuda_primer_ingreso, "field 'viewAyudaPrimerIngreso'");
        loginFragment.antiguaClaveLoginClaveVencida = (EditTextValidator) finder.findRequiredView(obj, R.id.f139loginformClaveVencidaantiguaClave, "field 'antiguaClaveLoginClaveVencida'");
        loginFragment.nuevaClaveLoginClaveVencida = (EditTextValidator) finder.findRequiredView(obj, R.id.f141loginformClaveVencidanuevaClave, "field 'nuevaClaveLoginClaveVencida'");
        loginFragment.reingresaClaveLoginClaveVencida = (EditTextValidator) finder.findRequiredView(obj, R.id.f143loginformClaveVencidareingresaClave, "field 'reingresaClaveLoginClaveVencida'");
        loginFragment.antiguoUsuarioLoginClaveVencida = (EditTextValidator) finder.findRequiredView(obj, R.id.f140loginformClaveVencidaantiguoUsuario, "field 'antiguoUsuarioLoginClaveVencida'");
        loginFragment.nuevoUsuarioLoginClaveVencida = (EditTextValidator) finder.findRequiredView(obj, R.id.f142loginformClaveVencidanuevoUsuario, "field 'nuevoUsuarioLoginClaveVencida'");
        loginFragment.reingresaUsuarioLoginClaveVencida = (EditTextValidator) finder.findRequiredView(obj, R.id.f144loginformClaveVencidareingresaUsuario, "field 'reingresaUsuarioLoginClaveVencida'");
        loginFragment.viewAyudaClaveVencida = (ImageView) finder.findRequiredView(obj, R.id.view_ayuda_claveVencida, "field 'viewAyudaClaveVencida'");
        loginFragment.documentoLoginAltaUsuario = (EditTextValidator) finder.findRequiredView(obj, R.id.f133loginformAltaUsuarionumDocumento, "field 'documentoLoginAltaUsuario'");
        loginFragment.claveLoginAltaUsuario = (EditTextValidator) finder.findRequiredView(obj, R.id.f132loginformAltaUsuarioclave, "field 'claveLoginAltaUsuario'");
        loginFragment.generaUsuarioLoginAltaUsuario = (EditTextValidator) finder.findRequiredView(obj, R.id.f135loginformAltaUsuariousuario, "field 'generaUsuarioLoginAltaUsuario'");
        loginFragment.regeneraUsuarioLoginAltaUsuario = (EditTextValidator) finder.findRequiredView(obj, R.id.f134loginformAltaUsuarioreusuario, "field 'regeneraUsuarioLoginAltaUsuario'");
        loginFragment.fechaNacimientoLoginAltaUsuario = (EditTextValidator) finder.findRequiredView(obj, R.id.f130loginformAltaUSuariofechaNacimiento, "field 'fechaNacimientoLoginAltaUsuario'");
        loginFragment.fechaNacimientoLoginAltaUsuarioSeparator = finder.findRequiredView(obj, R.id.f131loginformAltaUSuariofechaNacimientoseparator, "field 'fechaNacimientoLoginAltaUsuarioSeparator'");
        loginFragment.viewAyudaAltaUsuario = (ImageView) finder.findRequiredView(obj, R.id.view_ayuda_altaUsuario, "field 'viewAyudaAltaUsuario'");
        loginFragment.antiguoUsuarioLoginCambioUsuario = (EditTextValidator) finder.findRequiredView(obj, R.id.f136loginformCambioUsuarioantiguoUsuario, "field 'antiguoUsuarioLoginCambioUsuario'");
        loginFragment.nuevoUsuarioLoginCambioUsuario = (EditTextValidator) finder.findRequiredView(obj, R.id.f137loginformCambioUsuarionuevoUsuario, "field 'nuevoUsuarioLoginCambioUsuario'");
        loginFragment.reingresaUsuarioLoginCambioUsuario = (EditTextValidator) finder.findRequiredView(obj, R.id.f138loginformCambioUsuarioreingresaUsuario, "field 'reingresaUsuarioLoginCambioUsuario'");
        loginFragment.viewAyudaCambioUsuario = (ImageView) finder.findRequiredView(obj, R.id.view_ayuda_cambioUsuario, "field 'viewAyudaCambioUsuario'");
        loginFragment.recuerdaDocumentoLayout = (LinearLayout) finder.findRequiredView(obj, R.id.recuerdaDocumentoLayout, "field 'recuerdaDocumentoLayout'");
        loginFragment.recuerdaDocumentoLayoutNoTradicional = (LinearLayout) finder.findRequiredView(obj, R.id.recuerdaDocumentoLayoutNoTradicional, "field 'recuerdaDocumentoLayoutNoTradicional'");
        loginFragment.toggleRecuerdaDocumento = (ToggleButton) finder.findRequiredView(obj, R.id.toggleRecuerdaDocumento, "field 'toggleRecuerdaDocumento'");
        loginFragment.toggleRecuerdaDocumentoNoTradicional = (ToggleButton) finder.findRequiredView(obj, R.id.toggleRecuerdaDocumentoNoTradicional, "field 'toggleRecuerdaDocumentoNoTradicional'");
    }

    public static void reset(LoginFragment loginFragment) {
        loginFragment.mControlPager = null;
        loginFragment.topView = null;
        loginFragment.topViewNoTradicional = null;
        loginFragment.loginIngresar = null;
        loginFragment.loginIngresarNoTradicional = null;
        loginFragment.loginTextAction = null;
        loginFragment.loginPrimerIngresoTextAction = null;
        loginFragment.loginTextActionNoTradicional = null;
        loginFragment.loginTradicional = null;
        loginFragment.loginSinonimo = null;
        loginFragment.loginSinonimoCallToAction = null;
        loginFragment.loginClaveVencida = null;
        loginFragment.loginPrimerIngreso = null;
        loginFragment.loginAltaUsuario = null;
        loginFragment.loginCambioUsuario = null;
        loginFragment.documentoLoginTradicional = null;
        loginFragment.claveLoginTradicional = null;
        loginFragment.usuarioLoginTradicional = null;
        loginFragment.viewAyudaTradicional = null;
        loginFragment.documentoLoginSinonimo = null;
        loginFragment.fechaLoginSinonimo = null;
        loginFragment.claveLoginSinonimo = null;
        loginFragment.usuarioLoginSinonimo = null;
        loginFragment.viewAyudaSinonimo = null;
        loginFragment.documentoLoginSinonimoCA = null;
        loginFragment.fechaLoginSinonimoCA = null;
        loginFragment.claveLoginSinonimoCA = null;
        loginFragment.usuarioLoginSinonimoCA = null;
        loginFragment.reusuarioLoginSinonimoCA = null;
        loginFragment.viewAyudaSinonimoCA = null;
        loginFragment.documentoLoginPrimerIngreso = null;
        loginFragment.nuevaClaveLoginPrimerIngreso = null;
        loginFragment.reingresaClaveLoginPrimerIngreso = null;
        loginFragment.generaUsuarioLoginPrimerIngreso = null;
        loginFragment.reingresaUsuarioLoginPrimerIngreso = null;
        loginFragment.claveAntiguaLoginPrimerIngreso = null;
        loginFragment.fechaNacimientoLoginPrimerIngreso = null;
        loginFragment.fechaNacimientoLoginPrimerIngresoSeparator = null;
        loginFragment.viewAyudaPrimerIngreso = null;
        loginFragment.antiguaClaveLoginClaveVencida = null;
        loginFragment.nuevaClaveLoginClaveVencida = null;
        loginFragment.reingresaClaveLoginClaveVencida = null;
        loginFragment.antiguoUsuarioLoginClaveVencida = null;
        loginFragment.nuevoUsuarioLoginClaveVencida = null;
        loginFragment.reingresaUsuarioLoginClaveVencida = null;
        loginFragment.viewAyudaClaveVencida = null;
        loginFragment.documentoLoginAltaUsuario = null;
        loginFragment.claveLoginAltaUsuario = null;
        loginFragment.generaUsuarioLoginAltaUsuario = null;
        loginFragment.regeneraUsuarioLoginAltaUsuario = null;
        loginFragment.fechaNacimientoLoginAltaUsuario = null;
        loginFragment.fechaNacimientoLoginAltaUsuarioSeparator = null;
        loginFragment.viewAyudaAltaUsuario = null;
        loginFragment.antiguoUsuarioLoginCambioUsuario = null;
        loginFragment.nuevoUsuarioLoginCambioUsuario = null;
        loginFragment.reingresaUsuarioLoginCambioUsuario = null;
        loginFragment.viewAyudaCambioUsuario = null;
        loginFragment.recuerdaDocumentoLayout = null;
        loginFragment.recuerdaDocumentoLayoutNoTradicional = null;
        loginFragment.toggleRecuerdaDocumento = null;
        loginFragment.toggleRecuerdaDocumentoNoTradicional = null;
    }
}
