package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zzrg<R extends Result> extends OptionalPendingResult<R> {
    private final zzqe<R> a;

    public zzrg(PendingResult<R> pendingResult) {
        if (!(pendingResult instanceof zzqe)) {
            throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
        }
        this.a = (zzqe) pendingResult;
    }

    public R await() {
        return this.a.await();
    }

    public R await(long j, TimeUnit timeUnit) {
        return this.a.await(j, timeUnit);
    }

    public void cancel() {
        this.a.cancel();
    }

    public R get() {
        if (isDone()) {
            return await(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public boolean isCanceled() {
        return this.a.isCanceled();
    }

    public boolean isDone() {
        return this.a.isReady();
    }

    public void setResultCallback(ResultCallback<? super R> resultCallback) {
        this.a.setResultCallback(resultCallback);
    }

    public void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        this.a.setResultCallback(resultCallback, j, timeUnit);
    }

    @NonNull
    public <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> resultTransform) {
        return this.a.then(resultTransform);
    }

    public void zza(zza zza) {
        this.a.zza(zza);
    }

    public Integer zzaqf() {
        return this.a.zzaqf();
    }
}
